/* app.c generated by valac 0.10.0, the Vala compiler
 * generated from app.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "dbus-plugin.h"
#include <geanyplugin.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>

#define _g_free0(var) (var = (g_free (var), NULL))

struct _GeanyDBusApplicationPrivate {
	GeanyApp* app;
};


static gpointer geany_dbus_application_parent_class = NULL;

#define GEANY_DBUS_APPLICATION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GEANY_DBUS_TYPE_APPLICATION, GeanyDBusApplicationPrivate))
enum  {
	GEANY_DBUS_APPLICATION_DUMMY_PROPERTY
};
static void geany_dbus_application_finalize (GObject* obj);
static void geany_dbus_application_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static void _dbus_geany_dbus_application_get_debug_mode (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_geany_dbus_application_set_debug_mode (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_geany_dbus_application_get_configdir (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_geany_dbus_application_set_configdir (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_geany_dbus_application_get_datadir (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_geany_dbus_application_set_datadir (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_geany_dbus_application_get_docdir (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_geany_dbus_application_set_docdir (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static GVariant* geany_dbus_application_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean geany_dbus_application_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _geany_dbus_application_unregister_object (gpointer user_data);

static const GDBusArgInfo _geany_dbus_application_dbus_arg_info_get_debug_mode_result = {-1, "result", "b"};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_get_debug_mode_in[] = {NULL};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_get_debug_mode_out[] = {&_geany_dbus_application_dbus_arg_info_get_debug_mode_result, NULL};
static const GDBusMethodInfo _geany_dbus_application_dbus_method_info_get_debug_mode = {-1, "GetDebugMode", (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_get_debug_mode_in), (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_get_debug_mode_out)};
static const GDBusArgInfo _geany_dbus_application_dbus_arg_info_set_debug_mode_val = {-1, "val", "b"};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_set_debug_mode_in[] = {&_geany_dbus_application_dbus_arg_info_set_debug_mode_val, NULL};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_set_debug_mode_out[] = {NULL};
static const GDBusMethodInfo _geany_dbus_application_dbus_method_info_set_debug_mode = {-1, "SetDebugMode", (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_set_debug_mode_in), (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_set_debug_mode_out)};
static const GDBusArgInfo _geany_dbus_application_dbus_arg_info_get_configdir_result = {-1, "result", "s"};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_get_configdir_in[] = {NULL};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_get_configdir_out[] = {&_geany_dbus_application_dbus_arg_info_get_configdir_result, NULL};
static const GDBusMethodInfo _geany_dbus_application_dbus_method_info_get_configdir = {-1, "GetConfigdir", (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_get_configdir_in), (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_get_configdir_out)};
static const GDBusArgInfo _geany_dbus_application_dbus_arg_info_set_configdir_val = {-1, "val", "s"};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_set_configdir_in[] = {&_geany_dbus_application_dbus_arg_info_set_configdir_val, NULL};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_set_configdir_out[] = {NULL};
static const GDBusMethodInfo _geany_dbus_application_dbus_method_info_set_configdir = {-1, "SetConfigdir", (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_set_configdir_in), (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_set_configdir_out)};
static const GDBusArgInfo _geany_dbus_application_dbus_arg_info_get_datadir_result = {-1, "result", "s"};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_get_datadir_in[] = {NULL};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_get_datadir_out[] = {&_geany_dbus_application_dbus_arg_info_get_datadir_result, NULL};
static const GDBusMethodInfo _geany_dbus_application_dbus_method_info_get_datadir = {-1, "GetDatadir", (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_get_datadir_in), (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_get_datadir_out)};
static const GDBusArgInfo _geany_dbus_application_dbus_arg_info_set_datadir_val = {-1, "val", "s"};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_set_datadir_in[] = {&_geany_dbus_application_dbus_arg_info_set_datadir_val, NULL};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_set_datadir_out[] = {NULL};
static const GDBusMethodInfo _geany_dbus_application_dbus_method_info_set_datadir = {-1, "SetDatadir", (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_set_datadir_in), (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_set_datadir_out)};
static const GDBusArgInfo _geany_dbus_application_dbus_arg_info_get_docdir_result = {-1, "result", "s"};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_get_docdir_in[] = {NULL};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_get_docdir_out[] = {&_geany_dbus_application_dbus_arg_info_get_docdir_result, NULL};
static const GDBusMethodInfo _geany_dbus_application_dbus_method_info_get_docdir = {-1, "GetDocdir", (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_get_docdir_in), (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_get_docdir_out)};
static const GDBusArgInfo _geany_dbus_application_dbus_arg_info_set_docdir_val = {-1, "val", "s"};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_set_docdir_in[] = {&_geany_dbus_application_dbus_arg_info_set_docdir_val, NULL};
static const GDBusArgInfo * const _geany_dbus_application_dbus_arg_info_set_docdir_out[] = {NULL};
static const GDBusMethodInfo _geany_dbus_application_dbus_method_info_set_docdir = {-1, "SetDocdir", (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_set_docdir_in), (GDBusArgInfo **) (&_geany_dbus_application_dbus_arg_info_set_docdir_out)};
static const GDBusMethodInfo * const _geany_dbus_application_dbus_method_info[] = {&_geany_dbus_application_dbus_method_info_get_debug_mode, &_geany_dbus_application_dbus_method_info_set_debug_mode, &_geany_dbus_application_dbus_method_info_get_configdir, &_geany_dbus_application_dbus_method_info_set_configdir, &_geany_dbus_application_dbus_method_info_get_datadir, &_geany_dbus_application_dbus_method_info_set_datadir, &_geany_dbus_application_dbus_method_info_get_docdir, &_geany_dbus_application_dbus_method_info_set_docdir, NULL};
static const GDBusSignalInfo * const _geany_dbus_application_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _geany_dbus_application_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _geany_dbus_application_dbus_interface_info = {-1, "org.geany.DBus.Application", (GDBusMethodInfo **) (&_geany_dbus_application_dbus_method_info), (GDBusSignalInfo **) (&_geany_dbus_application_dbus_signal_info), (GDBusPropertyInfo **) (&_geany_dbus_application_dbus_property_info)};
static const GDBusInterfaceVTable _geany_dbus_application_dbus_interface_vtable = {geany_dbus_application_dbus_interface_method_call, geany_dbus_application_dbus_interface_get_property, geany_dbus_application_dbus_interface_set_property};


GeanyDBusApplication* geany_dbus_application_construct (GType object_type, GeanyApp* app) {
	GeanyDBusApplication * self;
	self = (GeanyDBusApplication*) g_object_new (object_type, NULL);
	self->priv->app = app;
	return self;
}


GeanyDBusApplication* geany_dbus_application_new (GeanyApp* app) {
	return geany_dbus_application_construct (GEANY_DBUS_TYPE_APPLICATION, app);
}


gboolean geany_dbus_application_get_debug_mode (GeanyDBusApplication* self) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (self->priv->app != NULL, FALSE);
	result = self->priv->app->debug_mode;
	return result;
}


void geany_dbus_application_set_debug_mode (GeanyDBusApplication* self, gboolean val) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (self->priv->app != NULL);
	self->priv->app->debug_mode = val;
}


const char* geany_dbus_application_get_configdir (GeanyDBusApplication* self) {
	const char* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (self->priv->app != NULL, "");
	result = self->priv->app->configdir;
	return result;
}


void geany_dbus_application_set_configdir (GeanyDBusApplication* self, const char* val) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (val != NULL);
	g_return_if_fail (self->priv->app != NULL);
	self->priv->app->configdir = (_tmp0_ = g_strdup (val), _g_free0 (self->priv->app->configdir), _tmp0_);
}


const char* geany_dbus_application_get_datadir (GeanyDBusApplication* self) {
	const char* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (self->priv->app != NULL, "");
	result = self->priv->app->datadir;
	return result;
}


void geany_dbus_application_set_datadir (GeanyDBusApplication* self, const char* val) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (val != NULL);
	g_return_if_fail (self->priv->app != NULL);
	self->priv->app->datadir = (_tmp0_ = g_strdup (val), _g_free0 (self->priv->app->datadir), _tmp0_);
}


const char* geany_dbus_application_get_docdir (GeanyDBusApplication* self) {
	const char* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (self->priv->app != NULL, "");
	result = self->priv->app->docdir;
	return result;
}


void geany_dbus_application_set_docdir (GeanyDBusApplication* self, const char* val) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (val != NULL);
	g_return_if_fail (self->priv->app != NULL);
	self->priv->app->docdir = (_tmp0_ = g_strdup (val), _g_free0 (self->priv->app->docdir), _tmp0_);
}


static void geany_dbus_application_class_init (GeanyDBusApplicationClass * klass) {
	geany_dbus_application_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GeanyDBusApplicationPrivate));
	G_OBJECT_CLASS (klass)->finalize = geany_dbus_application_finalize;
}


static void geany_dbus_application_instance_init (GeanyDBusApplication * self) {
	self->priv = GEANY_DBUS_APPLICATION_GET_PRIVATE (self);
}


static void geany_dbus_application_finalize (GObject* obj) {
	GeanyDBusApplication * self;
	self = GEANY_DBUS_APPLICATION (obj);
	G_OBJECT_CLASS (geany_dbus_application_parent_class)->finalize (obj);
}


GType geany_dbus_application_get_type (void) {
	static volatile gsize geany_dbus_application_type_id__volatile = 0;
	if (g_once_init_enter (&geany_dbus_application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GeanyDBusApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) geany_dbus_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GeanyDBusApplication), 0, (GInstanceInitFunc) geany_dbus_application_instance_init, NULL };
		GType geany_dbus_application_type_id;
		geany_dbus_application_type_id = g_type_register_static (G_TYPE_OBJECT, "GeanyDBusApplication", &g_define_type_info, 0);
		g_once_init_leave (&geany_dbus_application_type_id__volatile, geany_dbus_application_type_id);
	}
	return geany_dbus_application_type_id__volatile;
}


static void _dbus_geany_dbus_application_get_debug_mode (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error;
	gboolean result;
	GVariantIter _arguments_iter;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	error = NULL;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = geany_dbus_application_get_debug_mode (self);
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_boolean (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_method_invocation_return_value (invocation, _reply);
}


static void _dbus_geany_dbus_application_set_debug_mode (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error;
	gboolean val = FALSE;
	GVariant* _tmp0_;
	GVariantIter _arguments_iter;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	error = NULL;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp0_ = g_variant_iter_next_value (&_arguments_iter);
	val = g_variant_get_boolean (_tmp0_);
	g_variant_unref (_tmp0_);
	geany_dbus_application_set_debug_mode (self, val);
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_method_invocation_return_value (invocation, _reply);
}


static void _dbus_geany_dbus_application_get_configdir (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error;
	const char* result;
	GVariantIter _arguments_iter;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	error = NULL;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = geany_dbus_application_get_configdir (self);
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_string (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_method_invocation_return_value (invocation, _reply);
}


static void _dbus_geany_dbus_application_set_configdir (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error;
	char* val = NULL;
	GVariant* _tmp1_;
	GVariantIter _arguments_iter;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	error = NULL;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp1_ = g_variant_iter_next_value (&_arguments_iter);
	val = g_variant_dup_string (_tmp1_, NULL);
	g_variant_unref (_tmp1_);
	geany_dbus_application_set_configdir (self, val);
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_g_free0 (val);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_method_invocation_return_value (invocation, _reply);
}


static void _dbus_geany_dbus_application_get_datadir (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error;
	const char* result;
	GVariantIter _arguments_iter;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	error = NULL;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = geany_dbus_application_get_datadir (self);
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_string (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_method_invocation_return_value (invocation, _reply);
}


static void _dbus_geany_dbus_application_set_datadir (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error;
	char* val = NULL;
	GVariant* _tmp2_;
	GVariantIter _arguments_iter;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	error = NULL;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp2_ = g_variant_iter_next_value (&_arguments_iter);
	val = g_variant_dup_string (_tmp2_, NULL);
	g_variant_unref (_tmp2_);
	geany_dbus_application_set_datadir (self, val);
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_g_free0 (val);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_method_invocation_return_value (invocation, _reply);
}


static void _dbus_geany_dbus_application_get_docdir (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error;
	const char* result;
	GVariantIter _arguments_iter;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	error = NULL;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = geany_dbus_application_get_docdir (self);
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_string (result));
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_method_invocation_return_value (invocation, _reply);
}


static void _dbus_geany_dbus_application_set_docdir (GeanyDBusApplication* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error;
	char* val = NULL;
	GVariant* _tmp3_;
	GVariantIter _arguments_iter;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	error = NULL;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp3_ = g_variant_iter_next_value (&_arguments_iter);
	val = g_variant_dup_string (_tmp3_, NULL);
	g_variant_unref (_tmp3_);
	geany_dbus_application_set_docdir (self, val);
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_g_free0 (val);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_method_invocation_return_value (invocation, _reply);
}


static void geany_dbus_application_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "GetDebugMode") == 0) {
		_dbus_geany_dbus_application_get_debug_mode (object, parameters, invocation);
	} else if (strcmp (method_name, "SetDebugMode") == 0) {
		_dbus_geany_dbus_application_set_debug_mode (object, parameters, invocation);
	} else if (strcmp (method_name, "GetConfigdir") == 0) {
		_dbus_geany_dbus_application_get_configdir (object, parameters, invocation);
	} else if (strcmp (method_name, "SetConfigdir") == 0) {
		_dbus_geany_dbus_application_set_configdir (object, parameters, invocation);
	} else if (strcmp (method_name, "GetDatadir") == 0) {
		_dbus_geany_dbus_application_get_datadir (object, parameters, invocation);
	} else if (strcmp (method_name, "SetDatadir") == 0) {
		_dbus_geany_dbus_application_set_datadir (object, parameters, invocation);
	} else if (strcmp (method_name, "GetDocdir") == 0) {
		_dbus_geany_dbus_application_get_docdir (object, parameters, invocation);
	} else if (strcmp (method_name, "SetDocdir") == 0) {
		_dbus_geany_dbus_application_set_docdir (object, parameters, invocation);
	}
}


static GVariant* geany_dbus_application_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean geany_dbus_application_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint geany_dbus_application_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, &_geany_dbus_application_dbus_interface_info, &_geany_dbus_application_dbus_interface_vtable, data, _geany_dbus_application_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _geany_dbus_application_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}




