/* dbus-plugin.c generated by valac 0.10.0, the Vala compiler
 * generated from dbus-plugin.vala, do not modify */

/*
 * plugin.vala
 * 
 * Copyright 2011 Matthew Brush <mbrush@leftclick.ca>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include "dbus-plugin.h"
#include <geanyplugin.h>
#include <stdlib.h>
#include <string.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))


GeanyPlugin* geany_plugin = NULL;
GeanyData* geany_data = NULL;
GeanyFunctions* geany_functions = NULL;
char* config_dir = NULL;
char* config_filename = NULL;
extern GeanyDBusServer* dbus_server;
GeanyDBusServer* dbus_server = NULL;




static void __geany_vala_plugin_SET_INFO (PluginInfo *self, const char* name, const char* description, const char* version, const char* author) {
	(*self).name = name;
	(*self).description = description;
	(*self).version = version;
	(*self).author = author;
}


void plugin_set_info (PluginInfo* info) {
	__geany_vala_plugin_SET_INFO (info, "DBus Interface", "Interact with Geany using the DBus.", "0.1", "Matthew Brush <mbrush@leftclick.ca>");
}


static gint __geany_vala_plugin_VERSION_CHECK (gint abi_version, gint api_required) {
	gint result = 0;
	if (abi_version != GEANY_ABI_VERSION) {
		result = -1;
		return result;
	}
	if (GEANY_API_VERSION < api_required) {
		result = api_required;
		return result;
	}
	result = 0;
	return result;
}


gint plugin_version_check (gint abi_version) {
	gint result = 0;
	result = __geany_vala_plugin_VERSION_CHECK (abi_version, 185);
	return result;
}


void plugin_init (GeanyData* data) {
	char* _tmp0_;
	char* _tmp1_;
	GeanyDBusServer* _tmp2_;
	g_return_if_fail (data != NULL);
	plugin_module_make_resident (geany_plugin);
	config_dir = (_tmp0_ = g_build_path (G_DIR_SEPARATOR_S, geany_data->app->configdir, "plugins", "dbus", NULL), _g_free0 (config_dir), _tmp0_);
	config_filename = (_tmp1_ = g_build_path (G_DIR_SEPARATOR_S, config_dir, "dbus.conf", NULL), _g_free0 (config_filename), _tmp1_);
	dbus_server = (_tmp2_ = geany_dbus_server_new (geany_plugin, geany_data, geany_functions), _g_object_unref0 (dbus_server), _tmp2_);
}


void plugin_cleanup (void) {
	geany_dbus_server_close (dbus_server);
	return;
}




