/* dbus-plugin.h generated by valac 0.10.0, the Vala compiler, do not modify */


#ifndef __DBUS_PLUGIN_H__
#define __DBUS_PLUGIN_H__

#include <glib.h>
#include <geanyplugin.h>
#include <stdlib.h>
#include <string.h>
#include <glib-object.h>

G_BEGIN_DECLS


#define GEANY_DBUS_TYPE_SERVER (geany_dbus_server_get_type ())
#define GEANY_DBUS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEANY_DBUS_TYPE_SERVER, GeanyDBusServer))
#define GEANY_DBUS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEANY_DBUS_TYPE_SERVER, GeanyDBusServerClass))
#define GEANY_DBUS_IS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEANY_DBUS_TYPE_SERVER))
#define GEANY_DBUS_IS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEANY_DBUS_TYPE_SERVER))
#define GEANY_DBUS_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEANY_DBUS_TYPE_SERVER, GeanyDBusServerClass))

typedef struct _GeanyDBusServer GeanyDBusServer;
typedef struct _GeanyDBusServerClass GeanyDBusServerClass;
typedef struct _GeanyDBusServerPrivate GeanyDBusServerPrivate;

#define GEANY_DBUS_TYPE_APPLICATION (geany_dbus_application_get_type ())
#define GEANY_DBUS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEANY_DBUS_TYPE_APPLICATION, GeanyDBusApplication))
#define GEANY_DBUS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEANY_DBUS_TYPE_APPLICATION, GeanyDBusApplicationClass))
#define GEANY_DBUS_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEANY_DBUS_TYPE_APPLICATION))
#define GEANY_DBUS_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEANY_DBUS_TYPE_APPLICATION))
#define GEANY_DBUS_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEANY_DBUS_TYPE_APPLICATION, GeanyDBusApplicationClass))

typedef struct _GeanyDBusApplication GeanyDBusApplication;
typedef struct _GeanyDBusApplicationClass GeanyDBusApplicationClass;

#define GEANY_DBUS_TYPE_INTERFACE_PREFS (geany_dbus_interface_prefs_get_type ())
#define GEANY_DBUS_INTERFACE_PREFS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEANY_DBUS_TYPE_INTERFACE_PREFS, GeanyDBusInterfacePrefs))
#define GEANY_DBUS_INTERFACE_PREFS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEANY_DBUS_TYPE_INTERFACE_PREFS, GeanyDBusInterfacePrefsClass))
#define GEANY_DBUS_IS_INTERFACE_PREFS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEANY_DBUS_TYPE_INTERFACE_PREFS))
#define GEANY_DBUS_IS_INTERFACE_PREFS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEANY_DBUS_TYPE_INTERFACE_PREFS))
#define GEANY_DBUS_INTERFACE_PREFS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEANY_DBUS_TYPE_INTERFACE_PREFS, GeanyDBusInterfacePrefsClass))

typedef struct _GeanyDBusInterfacePrefs GeanyDBusInterfacePrefs;
typedef struct _GeanyDBusInterfacePrefsClass GeanyDBusInterfacePrefsClass;

#define GEANY_DBUS_TYPE_PROJECT (geany_dbus_project_get_type ())
#define GEANY_DBUS_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEANY_DBUS_TYPE_PROJECT, GeanyDBusProject))
#define GEANY_DBUS_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEANY_DBUS_TYPE_PROJECT, GeanyDBusProjectClass))
#define GEANY_DBUS_IS_PROJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEANY_DBUS_TYPE_PROJECT))
#define GEANY_DBUS_IS_PROJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEANY_DBUS_TYPE_PROJECT))
#define GEANY_DBUS_PROJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEANY_DBUS_TYPE_PROJECT, GeanyDBusProjectClass))

typedef struct _GeanyDBusProject GeanyDBusProject;
typedef struct _GeanyDBusProjectClass GeanyDBusProjectClass;

#define GEANY_DBUS_TYPE_WIDGETS (geany_dbus_widgets_get_type ())
#define GEANY_DBUS_WIDGETS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEANY_DBUS_TYPE_WIDGETS, GeanyDBusWidgets))
#define GEANY_DBUS_WIDGETS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEANY_DBUS_TYPE_WIDGETS, GeanyDBusWidgetsClass))
#define GEANY_DBUS_IS_WIDGETS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEANY_DBUS_TYPE_WIDGETS))
#define GEANY_DBUS_IS_WIDGETS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEANY_DBUS_TYPE_WIDGETS))
#define GEANY_DBUS_WIDGETS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEANY_DBUS_TYPE_WIDGETS, GeanyDBusWidgetsClass))

typedef struct _GeanyDBusWidgets GeanyDBusWidgets;
typedef struct _GeanyDBusWidgetsClass GeanyDBusWidgetsClass;
typedef struct _GeanyDBusApplicationPrivate GeanyDBusApplicationPrivate;
typedef struct _GeanyDBusInterfacePrefsPrivate GeanyDBusInterfacePrefsPrivate;
typedef struct _GeanyDBusProjectPrivate GeanyDBusProjectPrivate;

#define GEANY_DBUS_TYPE_INDENT_PREFS (geany_dbus_indent_prefs_get_type ())
#define GEANY_DBUS_INDENT_PREFS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEANY_DBUS_TYPE_INDENT_PREFS, GeanyDBusIndentPrefs))
#define GEANY_DBUS_INDENT_PREFS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEANY_DBUS_TYPE_INDENT_PREFS, GeanyDBusIndentPrefsClass))
#define GEANY_DBUS_IS_INDENT_PREFS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEANY_DBUS_TYPE_INDENT_PREFS))
#define GEANY_DBUS_IS_INDENT_PREFS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEANY_DBUS_TYPE_INDENT_PREFS))
#define GEANY_DBUS_INDENT_PREFS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEANY_DBUS_TYPE_INDENT_PREFS, GeanyDBusIndentPrefsClass))

typedef struct _GeanyDBusIndentPrefs GeanyDBusIndentPrefs;
typedef struct _GeanyDBusIndentPrefsClass GeanyDBusIndentPrefsClass;
typedef struct _GeanyDBusIndentPrefsPrivate GeanyDBusIndentPrefsPrivate;

#define GEANY_DBUS_TYPE_DOCUMENT (geany_dbus_document_get_type ())
#define GEANY_DBUS_DOCUMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEANY_DBUS_TYPE_DOCUMENT, GeanyDBusDocument))
#define GEANY_DBUS_DOCUMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEANY_DBUS_TYPE_DOCUMENT, GeanyDBusDocumentClass))
#define GEANY_DBUS_IS_DOCUMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEANY_DBUS_TYPE_DOCUMENT))
#define GEANY_DBUS_IS_DOCUMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEANY_DBUS_TYPE_DOCUMENT))
#define GEANY_DBUS_DOCUMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEANY_DBUS_TYPE_DOCUMENT, GeanyDBusDocumentClass))

typedef struct _GeanyDBusDocument GeanyDBusDocument;
typedef struct _GeanyDBusDocumentClass GeanyDBusDocumentClass;
typedef struct _GeanyDBusDocumentPrivate GeanyDBusDocumentPrivate;
typedef struct _GeanyDBusWidgetsPrivate GeanyDBusWidgetsPrivate;

struct _GeanyDBusServer {
	GObject parent_instance;
	GeanyDBusServerPrivate * priv;
};

struct _GeanyDBusServerClass {
	GObjectClass parent_class;
};

struct _GeanyDBusApplication {
	GObject parent_instance;
	GeanyDBusApplicationPrivate * priv;
};

struct _GeanyDBusApplicationClass {
	GObjectClass parent_class;
};

struct _GeanyDBusInterfacePrefs {
	GObject parent_instance;
	GeanyDBusInterfacePrefsPrivate * priv;
};

struct _GeanyDBusInterfacePrefsClass {
	GObjectClass parent_class;
};

struct _GeanyDBusProject {
	GObject parent_instance;
	GeanyDBusProjectPrivate * priv;
};

struct _GeanyDBusProjectClass {
	GObjectClass parent_class;
};

struct _GeanyDBusIndentPrefs {
	GObject parent_instance;
	GeanyDBusIndentPrefsPrivate * priv;
};

struct _GeanyDBusIndentPrefsClass {
	GObjectClass parent_class;
};

struct _GeanyDBusDocument {
	GObject parent_instance;
	GeanyDBusDocumentPrivate * priv;
};

struct _GeanyDBusDocumentClass {
	GObjectClass parent_class;
};

struct _GeanyDBusWidgets {
	GObject parent_instance;
	GeanyDBusWidgetsPrivate * priv;
};

struct _GeanyDBusWidgetsClass {
	GObjectClass parent_class;
};


extern GeanyPlugin* geany_plugin;
extern GeanyData* geany_data;
extern GeanyFunctions* geany_functions;
extern char* config_dir;
extern char* config_filename;
void plugin_set_info (PluginInfo* info);
gint plugin_version_check (gint abi_version);
void plugin_init (GeanyData* data);
void plugin_cleanup (void);
GType geany_dbus_server_get_type (void) G_GNUC_CONST;
#define GEANY_DBUS_NAME "org.geany.DBus"
GeanyDBusServer* geany_dbus_server_new (GeanyPlugin* plugin, GeanyData* data, GeanyFunctions* functions);
GeanyDBusServer* geany_dbus_server_construct (GType object_type, GeanyPlugin* plugin, GeanyData* data, GeanyFunctions* functions);
void geany_dbus_server_close (GeanyDBusServer* self);
void geany_dbus_server_on_document_open_new (GObject* object, struct GeanyDocument* doc, GeanyDBusServer* self);
void geany_dbus_server_on_document_close (GObject* object, struct GeanyDocument* doc, GeanyDBusServer* self);
void geany_dbus_server_on_document_save (GObject* object, struct GeanyDocument* doc, GeanyDBusServer* self);
void geany_dbus_server_on_document_before_save (GObject* object, struct GeanyDocument* doc, GeanyDBusServer* self);
GType geany_dbus_application_get_type (void) G_GNUC_CONST;
guint geany_dbus_application_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GeanyDBusApplication* geany_dbus_server_get_application (GeanyDBusServer* self);
void geany_dbus_server_set_application (GeanyDBusServer* self, GeanyDBusApplication* value);
GType geany_dbus_interface_prefs_get_type (void) G_GNUC_CONST;
guint geany_dbus_interface_prefs_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GeanyDBusInterfacePrefs* geany_dbus_server_get_interface_prefs (GeanyDBusServer* self);
void geany_dbus_server_set_interface_prefs (GeanyDBusServer* self, GeanyDBusInterfacePrefs* value);
GType geany_dbus_project_get_type (void) G_GNUC_CONST;
guint geany_dbus_project_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GeanyDBusProject* geany_dbus_server_get_project (GeanyDBusServer* self);
void geany_dbus_server_set_project (GeanyDBusServer* self, GeanyDBusProject* value);
GType geany_dbus_widgets_get_type (void) G_GNUC_CONST;
guint geany_dbus_widgets_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GeanyDBusWidgets* geany_dbus_server_get_widgets (GeanyDBusServer* self);
void geany_dbus_server_set_widgets (GeanyDBusServer* self, GeanyDBusWidgets* value);
GeanyDBusApplication* geany_dbus_application_new (GeanyApp* app);
GeanyDBusApplication* geany_dbus_application_construct (GType object_type, GeanyApp* app);
gboolean geany_dbus_application_get_debug_mode (GeanyDBusApplication* self);
void geany_dbus_application_set_debug_mode (GeanyDBusApplication* self, gboolean val);
const char* geany_dbus_application_get_configdir (GeanyDBusApplication* self);
void geany_dbus_application_set_configdir (GeanyDBusApplication* self, const char* val);
const char* geany_dbus_application_get_datadir (GeanyDBusApplication* self);
void geany_dbus_application_set_datadir (GeanyDBusApplication* self, const char* val);
const char* geany_dbus_application_get_docdir (GeanyDBusApplication* self);
void geany_dbus_application_set_docdir (GeanyDBusApplication* self, const char* val);
GeanyDBusInterfacePrefs* geany_dbus_interface_prefs_new (GeanyInterfacePrefs* prefs);
GeanyDBusInterfacePrefs* geany_dbus_interface_prefs_construct (GType object_type, GeanyInterfacePrefs* prefs);
gboolean geany_dbus_interface_prefs_get_sidebar_symbol_visible (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_sidebar_symbol_visible (GeanyDBusInterfacePrefs* self, gboolean val);
gboolean geany_dbus_interface_prefs_get_sidebar_openfiles_visible (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_sidebar_openfiles_visible (GeanyDBusInterfacePrefs* self, gboolean val);
const char* geany_dbus_interface_prefs_get_editor_font (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_editor_font (GeanyDBusInterfacePrefs* self, const char* val);
const char* geany_dbus_interface_prefs_get_tagbar_font (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_tagbar_font (GeanyDBusInterfacePrefs* self, const char* val);
const char* geany_dbus_interface_prefs_get_msgwin_font (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_msgwin_font (GeanyDBusInterfacePrefs* self, const char* val);
gboolean geany_dbus_interface_prefs_get_show_notebook_tabs (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_show_notebook_tabs (GeanyDBusInterfacePrefs* self, gboolean val);
gint geany_dbus_interface_prefs_get_tab_pos_editor (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_tab_pos_editor (GeanyDBusInterfacePrefs* self, gint val);
gint geany_dbus_interface_prefs_get_tab_pos_msgwin (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_tab_pos_msgwin (GeanyDBusInterfacePrefs* self, gint val);
gint geany_dbus_interface_prefs_get_tab_pos_sidebar (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_tab_pos_sidebar (GeanyDBusInterfacePrefs* self, gint val);
gboolean geany_dbus_interface_prefs_get_statusbar_visible (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_statusbar_visible (GeanyDBusInterfacePrefs* self, gboolean val);
gboolean geany_dbus_interface_prefs_get_show_symbol_list_expanders (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_show_symbol_list_expanders (GeanyDBusInterfacePrefs* self, gboolean val);
gboolean geany_dbus_interface_prefs_get_notebook_double_click_hides_widgets (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_notebook_double_click_hides_widgets (GeanyDBusInterfacePrefs* self, gboolean val);
gboolean geany_dbus_interface_prefs_get_highlighting_invert_all (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_highlighting_invert_all (GeanyDBusInterfacePrefs* self, gboolean val);
gint geany_dbus_interface_prefs_get_sidebar_pos (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_sidebar_pos (GeanyDBusInterfacePrefs* self, gint val);
gboolean geany_dbus_interface_prefs_get_msgwin_status_visible (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_msgwin_status_visible (GeanyDBusInterfacePrefs* self, gboolean val);
gboolean geany_dbus_interface_prefs_get_msgwin_compiler_visible (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_msgwin_compiler_visible (GeanyDBusInterfacePrefs* self, gboolean val);
gboolean geany_dbus_interface_prefs_get_msgwin_messages_visible (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_msgwin_messages_visible (GeanyDBusInterfacePrefs* self, gboolean val);
gboolean geany_dbus_interface_prefs_get_msgwin_scribble_visible (GeanyDBusInterfacePrefs* self);
void geany_dbus_interface_prefs_set_msgwin_scribble_visible (GeanyDBusInterfacePrefs* self, gboolean val);
GeanyDBusProject* geany_dbus_project_new (GeanyProject* proj);
GeanyDBusProject* geany_dbus_project_construct (GType object_type, GeanyProject* proj);
const char* geany_dbus_project_get_name (GeanyDBusProject* self);
void geany_dbus_project_set_name (GeanyDBusProject* self, const char* val);
const char* geany_dbus_project_get_description (GeanyDBusProject* self);
void geany_dbus_project_set_description (GeanyDBusProject* self, const char* val);
const char* geany_dbus_project_get_file_name (GeanyDBusProject* self);
void geany_dbus_project_set_file_name (GeanyDBusProject* self, const char* val);
const char* geany_dbus_project_get_base_path (GeanyDBusProject* self);
void geany_dbus_project_set_base_path (GeanyDBusProject* self, const char* val);
gint geany_dbus_project_get_project_type (GeanyDBusProject* self);
void geany_dbus_project_set_project_type (GeanyDBusProject* self, gint val);
GType geany_dbus_indent_prefs_get_type (void) G_GNUC_CONST;
guint geany_dbus_indent_prefs_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GeanyDBusIndentPrefs* geany_dbus_indent_prefs_new (GeanyIndentPrefs* prefs);
GeanyDBusIndentPrefs* geany_dbus_indent_prefs_construct (GType object_type, GeanyIndentPrefs* prefs);
gint geany_dbus_indent_prefs_get_width (GeanyDBusIndentPrefs* self);
void geany_dbus_indent_prefs_set_width (GeanyDBusIndentPrefs* self, gint val);
GeanyIndentType geany_dbus_indent_prefs_get_indent_type (GeanyDBusIndentPrefs* self);
void geany_dbus_indent_prefs_set_indent_type (GeanyDBusIndentPrefs* self, GeanyIndentType val);
gint geany_dbus_indent_prefs_get_hard_tab_width (GeanyDBusIndentPrefs* self);
void geany_dbus_indent_prefs_set_hard_tab_width (GeanyDBusIndentPrefs* self, gint val);
GeanyAutoIndent geany_dbus_indent_prefs_get_auto_indent_mode (GeanyDBusIndentPrefs* self);
void geany_dbus_indent_prefs_set_auto_indent_mode (GeanyDBusIndentPrefs* self, GeanyAutoIndent val);
gboolean geany_dbus_indent_prefs_get_detect_type (GeanyDBusIndentPrefs* self);
void geany_dbus_indent_prefs_set_detect_type (GeanyDBusIndentPrefs* self, gboolean val);
GType geany_dbus_document_get_type (void) G_GNUC_CONST;
guint geany_dbus_document_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GeanyDBusDocument* geany_dbus_document_new (struct GeanyDocument* doc);
GeanyDBusDocument* geany_dbus_document_construct (GType object_type, struct GeanyDocument* doc);
guint geany_dbus_document_get_dbus_index (GeanyDBusDocument* self);
void geany_dbus_document_set_dbus_index (GeanyDBusDocument* self, guint value);
gboolean geany_dbus_document_get_is_valid (GeanyDBusDocument* self);
gint geany_dbus_document_get_index (GeanyDBusDocument* self);
const char* geany_dbus_document_get_file_name (GeanyDBusDocument* self);
void geany_dbus_document_set_text (GeanyDBusDocument* self, const char* value);
guint geany_dbus_document_get_text_length (GeanyDBusDocument* self);
GeanyDBusWidgets* geany_dbus_widgets_new (GeanyMainWidgets* widgets);
GeanyDBusWidgets* geany_dbus_widgets_construct (GType object_type, GeanyMainWidgets* widgets);


G_END_DECLS

#endif
