/* document.c generated by valac 0.10.0, the Vala compiler
 * generated from document.vala, do not modify */

/*
 * document.vala - Geany document interface for DBus plugin
 * 
 * Copyright 2011 Matthew Brush <mbrush@leftclick.ca>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include "dbus-plugin.h"
#include <geanyplugin.h>
#include <gio/gio.h>

#define _g_free0(var) (var = (g_free (var), NULL))

struct _GeanyDBusDocumentPrivate {
	struct GeanyDocument* doc;
	guint _dbus_index;
};


static gpointer geany_dbus_document_parent_class = NULL;

#define GEANY_DBUS_DOCUMENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GEANY_DBUS_TYPE_DOCUMENT, GeanyDBusDocumentPrivate))
enum  {
	GEANY_DBUS_DOCUMENT_DUMMY_PROPERTY,
	GEANY_DBUS_DOCUMENT_DBUS_INDEX,
	GEANY_DBUS_DOCUMENT_NEEDS_SAVING,
	GEANY_DBUS_DOCUMENT_ENCODING,
	GEANY_DBUS_DOCUMENT_FILE_NAME,
	GEANY_DBUS_DOCUMENT_FILE_TYPE,
	GEANY_DBUS_DOCUMENT_HAS_BOM,
	GEANY_DBUS_DOCUMENT_HAS_TAGS,
	GEANY_DBUS_DOCUMENT_INDEX,
	GEANY_DBUS_DOCUMENT_IS_VALID,
	GEANY_DBUS_DOCUMENT_IS_READ_ONLY,
	GEANY_DBUS_DOCUMENT_REAL_PATH,
	GEANY_DBUS_DOCUMENT_NOTEBOOK_PAGE
};
guint geany_dbus_document_get_dbus_index (GeanyDBusDocument* self);
void geany_dbus_document_set_dbus_index (GeanyDBusDocument* self, guint value);
static void geany_dbus_document_finalize (GObject* obj);
static void geany_dbus_document_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void geany_dbus_document_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void geany_dbus_document_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* geany_dbus_document_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static GVariant* _dbus_geany_dbus_document_get_needs_saving (GeanyDBusDocument* self);
static GVariant* _dbus_geany_dbus_document_get_encoding (GeanyDBusDocument* self);
static GVariant* _dbus_geany_dbus_document_get_file_name (GeanyDBusDocument* self);
static GVariant* _dbus_geany_dbus_document_get_file_type (GeanyDBusDocument* self);
static GVariant* _dbus_geany_dbus_document_get_has_bom (GeanyDBusDocument* self);
static GVariant* _dbus_geany_dbus_document_get_has_tags (GeanyDBusDocument* self);
static GVariant* _dbus_geany_dbus_document_get_index (GeanyDBusDocument* self);
static GVariant* _dbus_geany_dbus_document_get_is_valid (GeanyDBusDocument* self);
static GVariant* _dbus_geany_dbus_document_get_is_read_only (GeanyDBusDocument* self);
static GVariant* _dbus_geany_dbus_document_get_real_path (GeanyDBusDocument* self);
static GVariant* _dbus_geany_dbus_document_get_notebook_page (GeanyDBusDocument* self);
static gboolean geany_dbus_document_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _dbus_geany_dbus_document_set_needs_saving (GeanyDBusDocument* self, GVariant* _value);
static void _dbus_geany_dbus_document_set_encoding (GeanyDBusDocument* self, GVariant* _value);
static void _dbus_geany_dbus_document_set_is_read_only (GeanyDBusDocument* self, GVariant* _value);
static void _dbus_geany_dbus_document_shown (GObject* _sender, gpointer* _data);
static void _dbus_geany_dbus_document_before_close (GObject* _sender, gpointer* _data);
static void _dbus_geany_dbus_document_before_save (GObject* _sender, gpointer* _data);
static void _dbus_geany_dbus_document_saved (GObject* _sender, gpointer* _data);
static void _dbus_geany_dbus_document_file_type_set (GObject* _sender, gpointer* _data);
static void _dbus_geany_dbus_document_update_editor_menu (GObject* _sender, gpointer* _data);
static void _geany_dbus_document_unregister_object (gpointer user_data);

static const GDBusMethodInfo * const _geany_dbus_document_dbus_method_info[] = {NULL};
static const GDBusArgInfo * const _geany_dbus_document_dbus_arg_info_shown[] = {NULL};
static const GDBusSignalInfo _geany_dbus_document_dbus_signal_info_shown = {-1, "Shown", (GDBusArgInfo **) (&_geany_dbus_document_dbus_arg_info_shown)};
static const GDBusArgInfo * const _geany_dbus_document_dbus_arg_info_before_close[] = {NULL};
static const GDBusSignalInfo _geany_dbus_document_dbus_signal_info_before_close = {-1, "BeforeClose", (GDBusArgInfo **) (&_geany_dbus_document_dbus_arg_info_before_close)};
static const GDBusArgInfo * const _geany_dbus_document_dbus_arg_info_before_save[] = {NULL};
static const GDBusSignalInfo _geany_dbus_document_dbus_signal_info_before_save = {-1, "BeforeSave", (GDBusArgInfo **) (&_geany_dbus_document_dbus_arg_info_before_save)};
static const GDBusArgInfo * const _geany_dbus_document_dbus_arg_info_saved[] = {NULL};
static const GDBusSignalInfo _geany_dbus_document_dbus_signal_info_saved = {-1, "Saved", (GDBusArgInfo **) (&_geany_dbus_document_dbus_arg_info_saved)};
static const GDBusArgInfo * const _geany_dbus_document_dbus_arg_info_file_type_set[] = {NULL};
static const GDBusSignalInfo _geany_dbus_document_dbus_signal_info_file_type_set = {-1, "FileTypeSet", (GDBusArgInfo **) (&_geany_dbus_document_dbus_arg_info_file_type_set)};
static const GDBusArgInfo * const _geany_dbus_document_dbus_arg_info_update_editor_menu[] = {NULL};
static const GDBusSignalInfo _geany_dbus_document_dbus_signal_info_update_editor_menu = {-1, "UpdateEditorMenu", (GDBusArgInfo **) (&_geany_dbus_document_dbus_arg_info_update_editor_menu)};
static const GDBusSignalInfo * const _geany_dbus_document_dbus_signal_info[] = {&_geany_dbus_document_dbus_signal_info_shown, &_geany_dbus_document_dbus_signal_info_before_close, &_geany_dbus_document_dbus_signal_info_before_save, &_geany_dbus_document_dbus_signal_info_saved, &_geany_dbus_document_dbus_signal_info_file_type_set, &_geany_dbus_document_dbus_signal_info_update_editor_menu, NULL};
static const GDBusPropertyInfo _geany_dbus_document_dbus_property_info_needs_saving = {-1, "NeedsSaving", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_document_dbus_property_info_encoding = {-1, "Encoding", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_document_dbus_property_info_file_name = {-1, "FileName", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo _geany_dbus_document_dbus_property_info_file_type = {-1, "FileType", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo _geany_dbus_document_dbus_property_info_has_bom = {-1, "HasBom", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo _geany_dbus_document_dbus_property_info_has_tags = {-1, "HasTags", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo _geany_dbus_document_dbus_property_info_index = {-1, "Index", "i", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo _geany_dbus_document_dbus_property_info_is_valid = {-1, "IsValid", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo _geany_dbus_document_dbus_property_info_is_read_only = {-1, "IsReadOnly", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_document_dbus_property_info_real_path = {-1, "RealPath", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo _geany_dbus_document_dbus_property_info_notebook_page = {-1, "NotebookPage", "i", G_DBUS_PROPERTY_INFO_FLAGS_READABLE};
static const GDBusPropertyInfo * const _geany_dbus_document_dbus_property_info[] = {&_geany_dbus_document_dbus_property_info_needs_saving, &_geany_dbus_document_dbus_property_info_encoding, &_geany_dbus_document_dbus_property_info_file_name, &_geany_dbus_document_dbus_property_info_file_type, &_geany_dbus_document_dbus_property_info_has_bom, &_geany_dbus_document_dbus_property_info_has_tags, &_geany_dbus_document_dbus_property_info_index, &_geany_dbus_document_dbus_property_info_is_valid, &_geany_dbus_document_dbus_property_info_is_read_only, &_geany_dbus_document_dbus_property_info_real_path, &_geany_dbus_document_dbus_property_info_notebook_page, NULL};
static const GDBusInterfaceInfo _geany_dbus_document_dbus_interface_info = {-1, "org.geany.DBus.Document", (GDBusMethodInfo **) (&_geany_dbus_document_dbus_method_info), (GDBusSignalInfo **) (&_geany_dbus_document_dbus_signal_info), (GDBusPropertyInfo **) (&_geany_dbus_document_dbus_property_info)};
static const GDBusInterfaceVTable _geany_dbus_document_dbus_interface_vtable = {geany_dbus_document_dbus_interface_method_call, geany_dbus_document_dbus_interface_get_property, geany_dbus_document_dbus_interface_set_property};


GeanyDBusDocument* geany_dbus_document_construct (GType object_type, struct GeanyDocument* doc) {
	GeanyDBusDocument * self;
	g_return_val_if_fail (doc != NULL, NULL);
	self = (GeanyDBusDocument*) g_object_new (object_type, NULL);
	self->priv->doc = doc;
	return self;
}


GeanyDBusDocument* geany_dbus_document_new (struct GeanyDocument* doc) {
	return geany_dbus_document_construct (GEANY_DBUS_TYPE_DOCUMENT, doc);
}


guint geany_dbus_document_get_dbus_index (GeanyDBusDocument* self) {
	guint result;
	g_return_val_if_fail (self != NULL, 0U);
	result = self->priv->_dbus_index;
	return result;
}


void geany_dbus_document_set_dbus_index (GeanyDBusDocument* self, guint value) {
	g_return_if_fail (self != NULL);
	self->priv->_dbus_index = value;
	g_object_notify ((GObject *) self, "dbus-index");
}


static gboolean document_get_changed (struct GeanyDocument* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->changed;
	return result;
}


static void _document_set_text_changed (struct GeanyDocument* self, gboolean value) {
	g_return_if_fail (self != NULL);
	document_set_text_changed (self, value);
}


gboolean geany_dbus_document_get_needs_saving (GeanyDBusDocument* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = document_get_changed (self->priv->doc);
	return result;
}


void geany_dbus_document_set_needs_saving (GeanyDBusDocument* self, gboolean value) {
	g_return_if_fail (self != NULL);
	_document_set_text_changed (self->priv->doc, value);
	g_object_notify ((GObject *) self, "needs-saving");
}


static const char* document_get_encoding (struct GeanyDocument* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->encoding;
	return result;
}


static void _document_set_encoding (struct GeanyDocument* self, const char* value) {
	g_return_if_fail (self != NULL);
	document_set_encoding (self, value);
}


const char* geany_dbus_document_get_encoding (GeanyDBusDocument* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = document_get_encoding (self->priv->doc);
	return result;
}


void geany_dbus_document_set_encoding (GeanyDBusDocument* self, const char* value) {
	g_return_if_fail (self != NULL);
	_document_set_encoding (self->priv->doc, value);
	g_object_notify ((GObject *) self, "encoding");
}


const char* geany_dbus_document_get_file_name (GeanyDBusDocument* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = DOC_FILENAME (self->priv->doc);
	return result;
}


static struct GeanyFiletype* document_get_file_type (struct GeanyDocument* self) {
	struct GeanyFiletype* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->file_type;
	return result;
}


static void _document_set_filetype (struct GeanyDocument* self, struct GeanyFiletype* value) {
	g_return_if_fail (self != NULL);
	document_set_filetype (self, value);
}


const char* geany_dbus_document_get_file_type (GeanyDBusDocument* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = document_get_file_type (self->priv->doc)->title;
	return result;
}


static gboolean document_get_has_bom (struct GeanyDocument* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->has_bom;
	return result;
}


gboolean geany_dbus_document_get_has_bom (GeanyDBusDocument* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = document_get_has_bom (self->priv->doc);
	return result;
}


static gboolean document_get_has_tags (struct GeanyDocument* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->has_tags;
	return result;
}


gboolean geany_dbus_document_get_has_tags (GeanyDBusDocument* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = document_get_has_tags (self->priv->doc);
	return result;
}


static gint document_get_index (struct GeanyDocument* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->index;
	return result;
}


gint geany_dbus_document_get_index (GeanyDBusDocument* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = document_get_index (self->priv->doc);
	return result;
}


gboolean geany_dbus_document_get_is_valid (GeanyDBusDocument* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = DOC_VALID (self->priv->doc);
	return result;
}


gboolean geany_dbus_document_get_is_read_only (GeanyDBusDocument* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->doc->readonly;
	return result;
}


void geany_dbus_document_set_is_read_only (GeanyDBusDocument* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->doc->readonly = value;
	g_object_notify ((GObject *) self, "is-read-only");
}


static const char* document_get_real_path (struct GeanyDocument* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->real_path;
	return result;
}


const char* geany_dbus_document_get_real_path (GeanyDBusDocument* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = document_get_real_path (self->priv->doc);
	return result;
}


gint geany_dbus_document_get_notebook_page (GeanyDBusDocument* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = document_get_notebook_page (self->priv->doc);
	return result;
}


static void geany_dbus_document_class_init (GeanyDBusDocumentClass * klass) {
	geany_dbus_document_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GeanyDBusDocumentPrivate));
	G_OBJECT_CLASS (klass)->get_property = geany_dbus_document_get_property;
	G_OBJECT_CLASS (klass)->set_property = geany_dbus_document_set_property;
	G_OBJECT_CLASS (klass)->finalize = geany_dbus_document_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_DOCUMENT_DBUS_INDEX, g_param_spec_uint ("dbus-index", "dbus-index", "dbus-index", 0, G_MAXUINT, 0U, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_DOCUMENT_NEEDS_SAVING, g_param_spec_boolean ("needs-saving", "needs-saving", "needs-saving", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_DOCUMENT_ENCODING, g_param_spec_string ("encoding", "encoding", "encoding", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_DOCUMENT_FILE_NAME, g_param_spec_string ("file-name", "file-name", "file-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_DOCUMENT_FILE_TYPE, g_param_spec_string ("file-type", "file-type", "file-type", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_DOCUMENT_HAS_BOM, g_param_spec_boolean ("has-bom", "has-bom", "has-bom", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_DOCUMENT_HAS_TAGS, g_param_spec_boolean ("has-tags", "has-tags", "has-tags", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_DOCUMENT_INDEX, g_param_spec_int ("index", "index", "index", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_DOCUMENT_IS_VALID, g_param_spec_boolean ("is-valid", "is-valid", "is-valid", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_DOCUMENT_IS_READ_ONLY, g_param_spec_boolean ("is-read-only", "is-read-only", "is-read-only", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_DOCUMENT_REAL_PATH, g_param_spec_string ("real-path", "real-path", "real-path", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_DOCUMENT_NOTEBOOK_PAGE, g_param_spec_int ("notebook-page", "notebook-page", "notebook-page", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("shown", GEANY_DBUS_TYPE_DOCUMENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("before_close", GEANY_DBUS_TYPE_DOCUMENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("before_save", GEANY_DBUS_TYPE_DOCUMENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("saved", GEANY_DBUS_TYPE_DOCUMENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("file_type_set", GEANY_DBUS_TYPE_DOCUMENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("update_editor_menu", GEANY_DBUS_TYPE_DOCUMENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void geany_dbus_document_instance_init (GeanyDBusDocument * self) {
	self->priv = GEANY_DBUS_DOCUMENT_GET_PRIVATE (self);
}


static void geany_dbus_document_finalize (GObject* obj) {
	GeanyDBusDocument * self;
	self = GEANY_DBUS_DOCUMENT (obj);
	G_OBJECT_CLASS (geany_dbus_document_parent_class)->finalize (obj);
}


GType geany_dbus_document_get_type (void) {
	static volatile gsize geany_dbus_document_type_id__volatile = 0;
	if (g_once_init_enter (&geany_dbus_document_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GeanyDBusDocumentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) geany_dbus_document_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GeanyDBusDocument), 0, (GInstanceInitFunc) geany_dbus_document_instance_init, NULL };
		GType geany_dbus_document_type_id;
		geany_dbus_document_type_id = g_type_register_static (G_TYPE_OBJECT, "GeanyDBusDocument", &g_define_type_info, 0);
		g_once_init_leave (&geany_dbus_document_type_id__volatile, geany_dbus_document_type_id);
	}
	return geany_dbus_document_type_id__volatile;
}


static void geany_dbus_document_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GeanyDBusDocument * self;
	self = GEANY_DBUS_DOCUMENT (object);
	switch (property_id) {
		case GEANY_DBUS_DOCUMENT_DBUS_INDEX:
		g_value_set_uint (value, geany_dbus_document_get_dbus_index (self));
		break;
		case GEANY_DBUS_DOCUMENT_NEEDS_SAVING:
		g_value_set_boolean (value, geany_dbus_document_get_needs_saving (self));
		break;
		case GEANY_DBUS_DOCUMENT_ENCODING:
		g_value_set_string (value, geany_dbus_document_get_encoding (self));
		break;
		case GEANY_DBUS_DOCUMENT_FILE_NAME:
		g_value_set_string (value, geany_dbus_document_get_file_name (self));
		break;
		case GEANY_DBUS_DOCUMENT_FILE_TYPE:
		g_value_set_string (value, geany_dbus_document_get_file_type (self));
		break;
		case GEANY_DBUS_DOCUMENT_HAS_BOM:
		g_value_set_boolean (value, geany_dbus_document_get_has_bom (self));
		break;
		case GEANY_DBUS_DOCUMENT_HAS_TAGS:
		g_value_set_boolean (value, geany_dbus_document_get_has_tags (self));
		break;
		case GEANY_DBUS_DOCUMENT_INDEX:
		g_value_set_int (value, geany_dbus_document_get_index (self));
		break;
		case GEANY_DBUS_DOCUMENT_IS_VALID:
		g_value_set_boolean (value, geany_dbus_document_get_is_valid (self));
		break;
		case GEANY_DBUS_DOCUMENT_IS_READ_ONLY:
		g_value_set_boolean (value, geany_dbus_document_get_is_read_only (self));
		break;
		case GEANY_DBUS_DOCUMENT_REAL_PATH:
		g_value_set_string (value, geany_dbus_document_get_real_path (self));
		break;
		case GEANY_DBUS_DOCUMENT_NOTEBOOK_PAGE:
		g_value_set_int (value, geany_dbus_document_get_notebook_page (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void geany_dbus_document_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GeanyDBusDocument * self;
	self = GEANY_DBUS_DOCUMENT (object);
	switch (property_id) {
		case GEANY_DBUS_DOCUMENT_DBUS_INDEX:
		geany_dbus_document_set_dbus_index (self, g_value_get_uint (value));
		break;
		case GEANY_DBUS_DOCUMENT_NEEDS_SAVING:
		geany_dbus_document_set_needs_saving (self, g_value_get_boolean (value));
		break;
		case GEANY_DBUS_DOCUMENT_ENCODING:
		geany_dbus_document_set_encoding (self, g_value_get_string (value));
		break;
		case GEANY_DBUS_DOCUMENT_IS_READ_ONLY:
		geany_dbus_document_set_is_read_only (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void geany_dbus_document_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
}


static GVariant* _dbus_geany_dbus_document_get_needs_saving (GeanyDBusDocument* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_document_get_needs_saving (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_document_get_encoding (GeanyDBusDocument* self) {
	const char* result;
	GVariant* _reply;
	result = geany_dbus_document_get_encoding (self);
	_reply = g_variant_new_string (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_document_get_file_name (GeanyDBusDocument* self) {
	const char* result;
	GVariant* _reply;
	result = geany_dbus_document_get_file_name (self);
	_reply = g_variant_new_string (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_document_get_file_type (GeanyDBusDocument* self) {
	const char* result;
	GVariant* _reply;
	result = geany_dbus_document_get_file_type (self);
	_reply = g_variant_new_string (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_document_get_has_bom (GeanyDBusDocument* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_document_get_has_bom (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_document_get_has_tags (GeanyDBusDocument* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_document_get_has_tags (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_document_get_index (GeanyDBusDocument* self) {
	gint result;
	GVariant* _reply;
	result = geany_dbus_document_get_index (self);
	_reply = g_variant_new_int32 (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_document_get_is_valid (GeanyDBusDocument* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_document_get_is_valid (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_document_get_is_read_only (GeanyDBusDocument* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_document_get_is_read_only (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_document_get_real_path (GeanyDBusDocument* self) {
	const char* result;
	GVariant* _reply;
	result = geany_dbus_document_get_real_path (self);
	_reply = g_variant_new_string (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_document_get_notebook_page (GeanyDBusDocument* self) {
	gint result;
	GVariant* _reply;
	result = geany_dbus_document_get_notebook_page (self);
	_reply = g_variant_new_int32 (result);
	return _reply;
}


static GVariant* geany_dbus_document_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (property_name, "NeedsSaving") == 0) {
		return _dbus_geany_dbus_document_get_needs_saving (object);
	} else if (strcmp (property_name, "Encoding") == 0) {
		return _dbus_geany_dbus_document_get_encoding (object);
	} else if (strcmp (property_name, "FileName") == 0) {
		return _dbus_geany_dbus_document_get_file_name (object);
	} else if (strcmp (property_name, "FileType") == 0) {
		return _dbus_geany_dbus_document_get_file_type (object);
	} else if (strcmp (property_name, "HasBom") == 0) {
		return _dbus_geany_dbus_document_get_has_bom (object);
	} else if (strcmp (property_name, "HasTags") == 0) {
		return _dbus_geany_dbus_document_get_has_tags (object);
	} else if (strcmp (property_name, "Index") == 0) {
		return _dbus_geany_dbus_document_get_index (object);
	} else if (strcmp (property_name, "IsValid") == 0) {
		return _dbus_geany_dbus_document_get_is_valid (object);
	} else if (strcmp (property_name, "IsReadOnly") == 0) {
		return _dbus_geany_dbus_document_get_is_read_only (object);
	} else if (strcmp (property_name, "RealPath") == 0) {
		return _dbus_geany_dbus_document_get_real_path (object);
	} else if (strcmp (property_name, "NotebookPage") == 0) {
		return _dbus_geany_dbus_document_get_notebook_page (object);
	}
	return NULL;
}


static void _dbus_geany_dbus_document_set_needs_saving (GeanyDBusDocument* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_document_set_needs_saving (self, value);
}


static void _dbus_geany_dbus_document_set_encoding (GeanyDBusDocument* self, GVariant* _value) {
	char* value = NULL;
	value = g_variant_dup_string (_value, NULL);
	geany_dbus_document_set_encoding (self, value);
	_g_free0 (value);
}


static void _dbus_geany_dbus_document_set_is_read_only (GeanyDBusDocument* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_document_set_is_read_only (self, value);
}


static gboolean geany_dbus_document_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (property_name, "NeedsSaving") == 0) {
		_dbus_geany_dbus_document_set_needs_saving (object, value);
		return TRUE;
	} else if (strcmp (property_name, "Encoding") == 0) {
		_dbus_geany_dbus_document_set_encoding (object, value);
		return TRUE;
	} else if (strcmp (property_name, "IsReadOnly") == 0) {
		_dbus_geany_dbus_document_set_is_read_only (object, value);
		return TRUE;
	}
	return FALSE;
}


static void _dbus_geany_dbus_document_shown (GObject* _sender, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.geany.DBus.Document", "Shown", _arguments, NULL);
}


static void _dbus_geany_dbus_document_before_close (GObject* _sender, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.geany.DBus.Document", "BeforeClose", _arguments, NULL);
}


static void _dbus_geany_dbus_document_before_save (GObject* _sender, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.geany.DBus.Document", "BeforeSave", _arguments, NULL);
}


static void _dbus_geany_dbus_document_saved (GObject* _sender, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.geany.DBus.Document", "Saved", _arguments, NULL);
}


static void _dbus_geany_dbus_document_file_type_set (GObject* _sender, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.geany.DBus.Document", "FileTypeSet", _arguments, NULL);
}


static void _dbus_geany_dbus_document_update_editor_menu (GObject* _sender, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.geany.DBus.Document", "UpdateEditorMenu", _arguments, NULL);
}


guint geany_dbus_document_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, &_geany_dbus_document_dbus_interface_info, &_geany_dbus_document_dbus_interface_vtable, data, _geany_dbus_document_unregister_object, error);
	if (!result) {
		return 0;
	}
	g_signal_connect (object, "shown", (GCallback) _dbus_geany_dbus_document_shown, data);
	g_signal_connect (object, "before-close", (GCallback) _dbus_geany_dbus_document_before_close, data);
	g_signal_connect (object, "before-save", (GCallback) _dbus_geany_dbus_document_before_save, data);
	g_signal_connect (object, "saved", (GCallback) _dbus_geany_dbus_document_saved, data);
	g_signal_connect (object, "file-type-set", (GCallback) _dbus_geany_dbus_document_file_type_set, data);
	g_signal_connect (object, "update-editor-menu", (GCallback) _dbus_geany_dbus_document_update_editor_menu, data);
	return result;
}


static void _geany_dbus_document_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}




