/* iface-prefs.c generated by valac 0.10.0, the Vala compiler
 * generated from iface-prefs.vala, do not modify */

/*
 * iface-prefs.vala - Geany InterfacePrefs interface for DBus plugin
 * 
 * Copyright 2011 Matthew Brush <mbrush@leftclick.ca>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include "dbus-plugin.h"
#include <geanyplugin.h>
#include <gio/gio.h>

#define _g_free0(var) (var = (g_free (var), NULL))

struct _GeanyDBusInterfacePreferencesPrivate {
	GeanyInterfacePrefs* prefs;
};


static gpointer geany_dbus_interface_preferences_parent_class = NULL;

#define GEANY_DBUS_INTERFACE_PREFERENCES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GEANY_DBUS_TYPE_INTERFACE_PREFERENCES, GeanyDBusInterfacePreferencesPrivate))
enum  {
	GEANY_DBUS_INTERFACE_PREFERENCES_DUMMY_PROPERTY,
	GEANY_DBUS_INTERFACE_PREFERENCES_SIDEBAR_SYMBOL_VISIBLE,
	GEANY_DBUS_INTERFACE_PREFERENCES_SIDEBAR_OPENFILES_VISIBLE,
	GEANY_DBUS_INTERFACE_PREFERENCES_EDITOR_FONT,
	GEANY_DBUS_INTERFACE_PREFERENCES_TAGBAR_FONT,
	GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_FONT,
	GEANY_DBUS_INTERFACE_PREFERENCES_SHOW_NOTEBOOK_TABS,
	GEANY_DBUS_INTERFACE_PREFERENCES_TAB_POS_EDITOR,
	GEANY_DBUS_INTERFACE_PREFERENCES_TAB_POS_MSGWIN,
	GEANY_DBUS_INTERFACE_PREFERENCES_TAB_POS_SIDEBAR,
	GEANY_DBUS_INTERFACE_PREFERENCES_STATUSBAR_VISIBLE,
	GEANY_DBUS_INTERFACE_PREFERENCES_SHOW_SYMBOL_LIST_EXPANDERS,
	GEANY_DBUS_INTERFACE_PREFERENCES_NOTEBOOK_DOUBLE_CLICK_HIDES_WIDGETS,
	GEANY_DBUS_INTERFACE_PREFERENCES_HIGHLIGHTING_INVERT_ALL,
	GEANY_DBUS_INTERFACE_PREFERENCES_SIDEBAR_POS,
	GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_STATUS_VISIBLE,
	GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_COMPILER_VISIBLE,
	GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_MESSAGES_VISIBLE,
	GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_SCRIBBLE_VISIBLE
};
static void geany_dbus_interface_preferences_finalize (GObject* obj);
static void geany_dbus_interface_preferences_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void geany_dbus_interface_preferences_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void geany_dbus_interface_preferences_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* geany_dbus_interface_preferences_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static GVariant* _dbus_geany_dbus_interface_preferences_get_sidebar_symbol_visible (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_sidebar_openfiles_visible (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_editor_font (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_tagbar_font (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_msgwin_font (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_show_notebook_tabs (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_tab_pos_editor (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_tab_pos_msgwin (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_tab_pos_sidebar (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_statusbar_visible (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_show_symbol_list_expanders (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_notebook_double_click_hides_widgets (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_highlighting_invert_all (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_sidebar_pos (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_msgwin_status_visible (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_msgwin_compiler_visible (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_msgwin_messages_visible (GeanyDBusInterfacePreferences* self);
static GVariant* _dbus_geany_dbus_interface_preferences_get_msgwin_scribble_visible (GeanyDBusInterfacePreferences* self);
static gboolean geany_dbus_interface_preferences_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _dbus_geany_dbus_interface_preferences_set_sidebar_symbol_visible (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_sidebar_openfiles_visible (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_editor_font (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_tagbar_font (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_msgwin_font (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_show_notebook_tabs (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_tab_pos_editor (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_tab_pos_msgwin (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_tab_pos_sidebar (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_statusbar_visible (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_show_symbol_list_expanders (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_notebook_double_click_hides_widgets (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_highlighting_invert_all (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_sidebar_pos (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_msgwin_status_visible (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_msgwin_compiler_visible (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_msgwin_messages_visible (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _dbus_geany_dbus_interface_preferences_set_msgwin_scribble_visible (GeanyDBusInterfacePreferences* self, GVariant* _value);
static void _geany_dbus_interface_preferences_unregister_object (gpointer user_data);

static const GDBusMethodInfo * const _geany_dbus_interface_preferences_dbus_method_info[] = {NULL};
static const GDBusSignalInfo * const _geany_dbus_interface_preferences_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_sidebar_symbol_visible = {-1, "SidebarSymbolVisible", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_sidebar_openfiles_visible = {-1, "SidebarOpenfilesVisible", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_editor_font = {-1, "EditorFont", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_tagbar_font = {-1, "TagbarFont", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_msgwin_font = {-1, "MsgwinFont", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_show_notebook_tabs = {-1, "ShowNotebookTabs", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_tab_pos_editor = {-1, "TabPosEditor", "i", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_tab_pos_msgwin = {-1, "TabPosMsgwin", "i", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_tab_pos_sidebar = {-1, "TabPosSidebar", "i", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_statusbar_visible = {-1, "StatusbarVisible", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_show_symbol_list_expanders = {-1, "ShowSymbolListExpanders", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_notebook_double_click_hides_widgets = {-1, "NotebookDoubleClickHidesWidgets", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_highlighting_invert_all = {-1, "HighlightingInvertAll", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_sidebar_pos = {-1, "SidebarPos", "i", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_msgwin_status_visible = {-1, "MsgwinStatusVisible", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_msgwin_compiler_visible = {-1, "MsgwinCompilerVisible", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_msgwin_messages_visible = {-1, "MsgwinMessagesVisible", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_interface_preferences_dbus_property_info_msgwin_scribble_visible = {-1, "MsgwinScribbleVisible", "b", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo * const _geany_dbus_interface_preferences_dbus_property_info[] = {&_geany_dbus_interface_preferences_dbus_property_info_sidebar_symbol_visible, &_geany_dbus_interface_preferences_dbus_property_info_sidebar_openfiles_visible, &_geany_dbus_interface_preferences_dbus_property_info_editor_font, &_geany_dbus_interface_preferences_dbus_property_info_tagbar_font, &_geany_dbus_interface_preferences_dbus_property_info_msgwin_font, &_geany_dbus_interface_preferences_dbus_property_info_show_notebook_tabs, &_geany_dbus_interface_preferences_dbus_property_info_tab_pos_editor, &_geany_dbus_interface_preferences_dbus_property_info_tab_pos_msgwin, &_geany_dbus_interface_preferences_dbus_property_info_tab_pos_sidebar, &_geany_dbus_interface_preferences_dbus_property_info_statusbar_visible, &_geany_dbus_interface_preferences_dbus_property_info_show_symbol_list_expanders, &_geany_dbus_interface_preferences_dbus_property_info_notebook_double_click_hides_widgets, &_geany_dbus_interface_preferences_dbus_property_info_highlighting_invert_all, &_geany_dbus_interface_preferences_dbus_property_info_sidebar_pos, &_geany_dbus_interface_preferences_dbus_property_info_msgwin_status_visible, &_geany_dbus_interface_preferences_dbus_property_info_msgwin_compiler_visible, &_geany_dbus_interface_preferences_dbus_property_info_msgwin_messages_visible, &_geany_dbus_interface_preferences_dbus_property_info_msgwin_scribble_visible, NULL};
static const GDBusInterfaceInfo _geany_dbus_interface_preferences_dbus_interface_info = {-1, "org.geany.DBus.Interfaces.InterfacePreferences", (GDBusMethodInfo **) (&_geany_dbus_interface_preferences_dbus_method_info), (GDBusSignalInfo **) (&_geany_dbus_interface_preferences_dbus_signal_info), (GDBusPropertyInfo **) (&_geany_dbus_interface_preferences_dbus_property_info)};
static const GDBusInterfaceVTable _geany_dbus_interface_preferences_dbus_interface_vtable = {geany_dbus_interface_preferences_dbus_interface_method_call, geany_dbus_interface_preferences_dbus_interface_get_property, geany_dbus_interface_preferences_dbus_interface_set_property};


GeanyDBusInterfacePreferences* geany_dbus_interface_preferences_construct (GType object_type, GeanyInterfacePrefs* prefs) {
	GeanyDBusInterfacePreferences * self;
	g_return_val_if_fail (prefs != NULL, NULL);
	self = (GeanyDBusInterfacePreferences*) g_object_new (object_type, NULL);
	self->priv->prefs = prefs;
	return self;
}


GeanyDBusInterfacePreferences* geany_dbus_interface_preferences_new (GeanyInterfacePrefs* prefs) {
	return geany_dbus_interface_preferences_construct (GEANY_DBUS_TYPE_INTERFACE_PREFERENCES, prefs);
}


gboolean geany_dbus_interface_preferences_get_sidebar_symbol_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->prefs->sidebar_symbol_visible;
	return result;
}


void geany_dbus_interface_preferences_set_sidebar_symbol_visible (GeanyDBusInterfacePreferences* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->sidebar_symbol_visible = value;
	g_object_notify ((GObject *) self, "sidebar-symbol-visible");
}


gboolean geany_dbus_interface_preferences_get_sidebar_openfiles_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->prefs->sidebar_openfiles_visible;
	return result;
}


void geany_dbus_interface_preferences_set_sidebar_openfiles_visible (GeanyDBusInterfacePreferences* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->sidebar_openfiles_visible = value;
	g_object_notify ((GObject *) self, "sidebar-openfiles-visible");
}


const char* geany_dbus_interface_preferences_get_editor_font (GeanyDBusInterfacePreferences* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->prefs->editor_font;
	return result;
}


void geany_dbus_interface_preferences_set_editor_font (GeanyDBusInterfacePreferences* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->prefs->editor_font = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->prefs->editor_font), _tmp0_);
	g_object_notify ((GObject *) self, "editor-font");
}


const char* geany_dbus_interface_preferences_get_tagbar_font (GeanyDBusInterfacePreferences* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->prefs->tagbar_font;
	return result;
}


void geany_dbus_interface_preferences_set_tagbar_font (GeanyDBusInterfacePreferences* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->prefs->tagbar_font = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->prefs->tagbar_font), _tmp0_);
	g_object_notify ((GObject *) self, "tagbar-font");
}


const char* geany_dbus_interface_preferences_get_msgwin_font (GeanyDBusInterfacePreferences* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->prefs->msgwin_font;
	return result;
}


void geany_dbus_interface_preferences_set_msgwin_font (GeanyDBusInterfacePreferences* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->prefs->msgwin_font = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->prefs->msgwin_font), _tmp0_);
	g_object_notify ((GObject *) self, "msgwin-font");
}


gboolean geany_dbus_interface_preferences_get_show_notebook_tabs (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->prefs->show_notebook_tabs;
	return result;
}


void geany_dbus_interface_preferences_set_show_notebook_tabs (GeanyDBusInterfacePreferences* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->show_notebook_tabs = value;
	g_object_notify ((GObject *) self, "show-notebook-tabs");
}


gint geany_dbus_interface_preferences_get_tab_pos_editor (GeanyDBusInterfacePreferences* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->prefs->tab_pos_editor;
	return result;
}


void geany_dbus_interface_preferences_set_tab_pos_editor (GeanyDBusInterfacePreferences* self, gint value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->tab_pos_editor = value;
	g_object_notify ((GObject *) self, "tab-pos-editor");
}


gint geany_dbus_interface_preferences_get_tab_pos_msgwin (GeanyDBusInterfacePreferences* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->prefs->tab_pos_msgwin;
	return result;
}


void geany_dbus_interface_preferences_set_tab_pos_msgwin (GeanyDBusInterfacePreferences* self, gint value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->tab_pos_msgwin = value;
	g_object_notify ((GObject *) self, "tab-pos-msgwin");
}


gint geany_dbus_interface_preferences_get_tab_pos_sidebar (GeanyDBusInterfacePreferences* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->prefs->tab_pos_sidebar;
	return result;
}


void geany_dbus_interface_preferences_set_tab_pos_sidebar (GeanyDBusInterfacePreferences* self, gint value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->tab_pos_sidebar = value;
	g_object_notify ((GObject *) self, "tab-pos-sidebar");
}


gboolean geany_dbus_interface_preferences_get_statusbar_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->prefs->statusbar_visible;
	return result;
}


void geany_dbus_interface_preferences_set_statusbar_visible (GeanyDBusInterfacePreferences* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->statusbar_visible = value;
	g_object_notify ((GObject *) self, "statusbar-visible");
}


gboolean geany_dbus_interface_preferences_get_show_symbol_list_expanders (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->prefs->show_symbol_list_expanders;
	return result;
}


void geany_dbus_interface_preferences_set_show_symbol_list_expanders (GeanyDBusInterfacePreferences* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->show_symbol_list_expanders = value;
	g_object_notify ((GObject *) self, "show-symbol-list-expanders");
}


gboolean geany_dbus_interface_preferences_get_notebook_double_click_hides_widgets (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->prefs->notebook_double_click_hides_widgets;
	return result;
}


void geany_dbus_interface_preferences_set_notebook_double_click_hides_widgets (GeanyDBusInterfacePreferences* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->notebook_double_click_hides_widgets = value;
	g_object_notify ((GObject *) self, "notebook-double-click-hides-widgets");
}


gboolean geany_dbus_interface_preferences_get_highlighting_invert_all (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->prefs->highlighting_invert_all;
	return result;
}


void geany_dbus_interface_preferences_set_highlighting_invert_all (GeanyDBusInterfacePreferences* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->highlighting_invert_all = value;
	g_object_notify ((GObject *) self, "highlighting-invert-all");
}


gint geany_dbus_interface_preferences_get_sidebar_pos (GeanyDBusInterfacePreferences* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->prefs->sidebar_pos;
	return result;
}


void geany_dbus_interface_preferences_set_sidebar_pos (GeanyDBusInterfacePreferences* self, gint value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->sidebar_pos = value;
	g_object_notify ((GObject *) self, "sidebar-pos");
}


gboolean geany_dbus_interface_preferences_get_msgwin_status_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->prefs->msgwin_status_visible;
	return result;
}


void geany_dbus_interface_preferences_set_msgwin_status_visible (GeanyDBusInterfacePreferences* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->msgwin_status_visible = value;
	g_object_notify ((GObject *) self, "msgwin-status-visible");
}


gboolean geany_dbus_interface_preferences_get_msgwin_compiler_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->prefs->msgwin_compiler_visible;
	return result;
}


void geany_dbus_interface_preferences_set_msgwin_compiler_visible (GeanyDBusInterfacePreferences* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->msgwin_compiler_visible = value;
	g_object_notify ((GObject *) self, "msgwin-compiler-visible");
}


gboolean geany_dbus_interface_preferences_get_msgwin_messages_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->prefs->msgwin_messages_visible;
	return result;
}


void geany_dbus_interface_preferences_set_msgwin_messages_visible (GeanyDBusInterfacePreferences* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->msgwin_messages_visible = value;
	g_object_notify ((GObject *) self, "msgwin-messages-visible");
}


gboolean geany_dbus_interface_preferences_get_msgwin_scribble_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->prefs->msgwin_scribble_visible;
	return result;
}


void geany_dbus_interface_preferences_set_msgwin_scribble_visible (GeanyDBusInterfacePreferences* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->prefs->msgwin_scribble_visible = value;
	g_object_notify ((GObject *) self, "msgwin-scribble-visible");
}


static void geany_dbus_interface_preferences_class_init (GeanyDBusInterfacePreferencesClass * klass) {
	geany_dbus_interface_preferences_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GeanyDBusInterfacePreferencesPrivate));
	G_OBJECT_CLASS (klass)->get_property = geany_dbus_interface_preferences_get_property;
	G_OBJECT_CLASS (klass)->set_property = geany_dbus_interface_preferences_set_property;
	G_OBJECT_CLASS (klass)->finalize = geany_dbus_interface_preferences_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_SIDEBAR_SYMBOL_VISIBLE, g_param_spec_boolean ("sidebar-symbol-visible", "sidebar-symbol-visible", "sidebar-symbol-visible", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_SIDEBAR_OPENFILES_VISIBLE, g_param_spec_boolean ("sidebar-openfiles-visible", "sidebar-openfiles-visible", "sidebar-openfiles-visible", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_EDITOR_FONT, g_param_spec_string ("editor-font", "editor-font", "editor-font", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_TAGBAR_FONT, g_param_spec_string ("tagbar-font", "tagbar-font", "tagbar-font", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_FONT, g_param_spec_string ("msgwin-font", "msgwin-font", "msgwin-font", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_SHOW_NOTEBOOK_TABS, g_param_spec_boolean ("show-notebook-tabs", "show-notebook-tabs", "show-notebook-tabs", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_TAB_POS_EDITOR, g_param_spec_int ("tab-pos-editor", "tab-pos-editor", "tab-pos-editor", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_TAB_POS_MSGWIN, g_param_spec_int ("tab-pos-msgwin", "tab-pos-msgwin", "tab-pos-msgwin", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_TAB_POS_SIDEBAR, g_param_spec_int ("tab-pos-sidebar", "tab-pos-sidebar", "tab-pos-sidebar", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_STATUSBAR_VISIBLE, g_param_spec_boolean ("statusbar-visible", "statusbar-visible", "statusbar-visible", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_SHOW_SYMBOL_LIST_EXPANDERS, g_param_spec_boolean ("show-symbol-list-expanders", "show-symbol-list-expanders", "show-symbol-list-expanders", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_NOTEBOOK_DOUBLE_CLICK_HIDES_WIDGETS, g_param_spec_boolean ("notebook-double-click-hides-widgets", "notebook-double-click-hides-widgets", "notebook-double-click-hides-widgets", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_HIGHLIGHTING_INVERT_ALL, g_param_spec_boolean ("highlighting-invert-all", "highlighting-invert-all", "highlighting-invert-all", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_SIDEBAR_POS, g_param_spec_int ("sidebar-pos", "sidebar-pos", "sidebar-pos", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_STATUS_VISIBLE, g_param_spec_boolean ("msgwin-status-visible", "msgwin-status-visible", "msgwin-status-visible", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_COMPILER_VISIBLE, g_param_spec_boolean ("msgwin-compiler-visible", "msgwin-compiler-visible", "msgwin-compiler-visible", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_MESSAGES_VISIBLE, g_param_spec_boolean ("msgwin-messages-visible", "msgwin-messages-visible", "msgwin-messages-visible", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_SCRIBBLE_VISIBLE, g_param_spec_boolean ("msgwin-scribble-visible", "msgwin-scribble-visible", "msgwin-scribble-visible", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void geany_dbus_interface_preferences_instance_init (GeanyDBusInterfacePreferences * self) {
	self->priv = GEANY_DBUS_INTERFACE_PREFERENCES_GET_PRIVATE (self);
}


static void geany_dbus_interface_preferences_finalize (GObject* obj) {
	GeanyDBusInterfacePreferences * self;
	self = GEANY_DBUS_INTERFACE_PREFERENCES (obj);
	G_OBJECT_CLASS (geany_dbus_interface_preferences_parent_class)->finalize (obj);
}


GType geany_dbus_interface_preferences_get_type (void) {
	static volatile gsize geany_dbus_interface_preferences_type_id__volatile = 0;
	if (g_once_init_enter (&geany_dbus_interface_preferences_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GeanyDBusInterfacePreferencesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) geany_dbus_interface_preferences_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GeanyDBusInterfacePreferences), 0, (GInstanceInitFunc) geany_dbus_interface_preferences_instance_init, NULL };
		GType geany_dbus_interface_preferences_type_id;
		geany_dbus_interface_preferences_type_id = g_type_register_static (G_TYPE_OBJECT, "GeanyDBusInterfacePreferences", &g_define_type_info, 0);
		g_once_init_leave (&geany_dbus_interface_preferences_type_id__volatile, geany_dbus_interface_preferences_type_id);
	}
	return geany_dbus_interface_preferences_type_id__volatile;
}


static void geany_dbus_interface_preferences_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GeanyDBusInterfacePreferences * self;
	self = GEANY_DBUS_INTERFACE_PREFERENCES (object);
	switch (property_id) {
		case GEANY_DBUS_INTERFACE_PREFERENCES_SIDEBAR_SYMBOL_VISIBLE:
		g_value_set_boolean (value, geany_dbus_interface_preferences_get_sidebar_symbol_visible (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_SIDEBAR_OPENFILES_VISIBLE:
		g_value_set_boolean (value, geany_dbus_interface_preferences_get_sidebar_openfiles_visible (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_EDITOR_FONT:
		g_value_set_string (value, geany_dbus_interface_preferences_get_editor_font (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_TAGBAR_FONT:
		g_value_set_string (value, geany_dbus_interface_preferences_get_tagbar_font (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_FONT:
		g_value_set_string (value, geany_dbus_interface_preferences_get_msgwin_font (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_SHOW_NOTEBOOK_TABS:
		g_value_set_boolean (value, geany_dbus_interface_preferences_get_show_notebook_tabs (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_TAB_POS_EDITOR:
		g_value_set_int (value, geany_dbus_interface_preferences_get_tab_pos_editor (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_TAB_POS_MSGWIN:
		g_value_set_int (value, geany_dbus_interface_preferences_get_tab_pos_msgwin (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_TAB_POS_SIDEBAR:
		g_value_set_int (value, geany_dbus_interface_preferences_get_tab_pos_sidebar (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_STATUSBAR_VISIBLE:
		g_value_set_boolean (value, geany_dbus_interface_preferences_get_statusbar_visible (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_SHOW_SYMBOL_LIST_EXPANDERS:
		g_value_set_boolean (value, geany_dbus_interface_preferences_get_show_symbol_list_expanders (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_NOTEBOOK_DOUBLE_CLICK_HIDES_WIDGETS:
		g_value_set_boolean (value, geany_dbus_interface_preferences_get_notebook_double_click_hides_widgets (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_HIGHLIGHTING_INVERT_ALL:
		g_value_set_boolean (value, geany_dbus_interface_preferences_get_highlighting_invert_all (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_SIDEBAR_POS:
		g_value_set_int (value, geany_dbus_interface_preferences_get_sidebar_pos (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_STATUS_VISIBLE:
		g_value_set_boolean (value, geany_dbus_interface_preferences_get_msgwin_status_visible (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_COMPILER_VISIBLE:
		g_value_set_boolean (value, geany_dbus_interface_preferences_get_msgwin_compiler_visible (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_MESSAGES_VISIBLE:
		g_value_set_boolean (value, geany_dbus_interface_preferences_get_msgwin_messages_visible (self));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_SCRIBBLE_VISIBLE:
		g_value_set_boolean (value, geany_dbus_interface_preferences_get_msgwin_scribble_visible (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void geany_dbus_interface_preferences_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GeanyDBusInterfacePreferences * self;
	self = GEANY_DBUS_INTERFACE_PREFERENCES (object);
	switch (property_id) {
		case GEANY_DBUS_INTERFACE_PREFERENCES_SIDEBAR_SYMBOL_VISIBLE:
		geany_dbus_interface_preferences_set_sidebar_symbol_visible (self, g_value_get_boolean (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_SIDEBAR_OPENFILES_VISIBLE:
		geany_dbus_interface_preferences_set_sidebar_openfiles_visible (self, g_value_get_boolean (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_EDITOR_FONT:
		geany_dbus_interface_preferences_set_editor_font (self, g_value_get_string (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_TAGBAR_FONT:
		geany_dbus_interface_preferences_set_tagbar_font (self, g_value_get_string (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_FONT:
		geany_dbus_interface_preferences_set_msgwin_font (self, g_value_get_string (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_SHOW_NOTEBOOK_TABS:
		geany_dbus_interface_preferences_set_show_notebook_tabs (self, g_value_get_boolean (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_TAB_POS_EDITOR:
		geany_dbus_interface_preferences_set_tab_pos_editor (self, g_value_get_int (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_TAB_POS_MSGWIN:
		geany_dbus_interface_preferences_set_tab_pos_msgwin (self, g_value_get_int (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_TAB_POS_SIDEBAR:
		geany_dbus_interface_preferences_set_tab_pos_sidebar (self, g_value_get_int (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_STATUSBAR_VISIBLE:
		geany_dbus_interface_preferences_set_statusbar_visible (self, g_value_get_boolean (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_SHOW_SYMBOL_LIST_EXPANDERS:
		geany_dbus_interface_preferences_set_show_symbol_list_expanders (self, g_value_get_boolean (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_NOTEBOOK_DOUBLE_CLICK_HIDES_WIDGETS:
		geany_dbus_interface_preferences_set_notebook_double_click_hides_widgets (self, g_value_get_boolean (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_HIGHLIGHTING_INVERT_ALL:
		geany_dbus_interface_preferences_set_highlighting_invert_all (self, g_value_get_boolean (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_SIDEBAR_POS:
		geany_dbus_interface_preferences_set_sidebar_pos (self, g_value_get_int (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_STATUS_VISIBLE:
		geany_dbus_interface_preferences_set_msgwin_status_visible (self, g_value_get_boolean (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_COMPILER_VISIBLE:
		geany_dbus_interface_preferences_set_msgwin_compiler_visible (self, g_value_get_boolean (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_MESSAGES_VISIBLE:
		geany_dbus_interface_preferences_set_msgwin_messages_visible (self, g_value_get_boolean (value));
		break;
		case GEANY_DBUS_INTERFACE_PREFERENCES_MSGWIN_SCRIBBLE_VISIBLE:
		geany_dbus_interface_preferences_set_msgwin_scribble_visible (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void geany_dbus_interface_preferences_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_sidebar_symbol_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_sidebar_symbol_visible (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_sidebar_openfiles_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_sidebar_openfiles_visible (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_editor_font (GeanyDBusInterfacePreferences* self) {
	const char* result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_editor_font (self);
	_reply = g_variant_new_string (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_tagbar_font (GeanyDBusInterfacePreferences* self) {
	const char* result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_tagbar_font (self);
	_reply = g_variant_new_string (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_msgwin_font (GeanyDBusInterfacePreferences* self) {
	const char* result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_msgwin_font (self);
	_reply = g_variant_new_string (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_show_notebook_tabs (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_show_notebook_tabs (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_tab_pos_editor (GeanyDBusInterfacePreferences* self) {
	gint result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_tab_pos_editor (self);
	_reply = g_variant_new_int32 (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_tab_pos_msgwin (GeanyDBusInterfacePreferences* self) {
	gint result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_tab_pos_msgwin (self);
	_reply = g_variant_new_int32 (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_tab_pos_sidebar (GeanyDBusInterfacePreferences* self) {
	gint result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_tab_pos_sidebar (self);
	_reply = g_variant_new_int32 (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_statusbar_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_statusbar_visible (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_show_symbol_list_expanders (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_show_symbol_list_expanders (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_notebook_double_click_hides_widgets (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_notebook_double_click_hides_widgets (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_highlighting_invert_all (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_highlighting_invert_all (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_sidebar_pos (GeanyDBusInterfacePreferences* self) {
	gint result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_sidebar_pos (self);
	_reply = g_variant_new_int32 (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_msgwin_status_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_msgwin_status_visible (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_msgwin_compiler_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_msgwin_compiler_visible (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_msgwin_messages_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_msgwin_messages_visible (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_interface_preferences_get_msgwin_scribble_visible (GeanyDBusInterfacePreferences* self) {
	gboolean result;
	GVariant* _reply;
	result = geany_dbus_interface_preferences_get_msgwin_scribble_visible (self);
	_reply = g_variant_new_boolean (result);
	return _reply;
}


static GVariant* geany_dbus_interface_preferences_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (property_name, "SidebarSymbolVisible") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_sidebar_symbol_visible (object);
	} else if (strcmp (property_name, "SidebarOpenfilesVisible") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_sidebar_openfiles_visible (object);
	} else if (strcmp (property_name, "EditorFont") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_editor_font (object);
	} else if (strcmp (property_name, "TagbarFont") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_tagbar_font (object);
	} else if (strcmp (property_name, "MsgwinFont") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_msgwin_font (object);
	} else if (strcmp (property_name, "ShowNotebookTabs") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_show_notebook_tabs (object);
	} else if (strcmp (property_name, "TabPosEditor") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_tab_pos_editor (object);
	} else if (strcmp (property_name, "TabPosMsgwin") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_tab_pos_msgwin (object);
	} else if (strcmp (property_name, "TabPosSidebar") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_tab_pos_sidebar (object);
	} else if (strcmp (property_name, "StatusbarVisible") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_statusbar_visible (object);
	} else if (strcmp (property_name, "ShowSymbolListExpanders") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_show_symbol_list_expanders (object);
	} else if (strcmp (property_name, "NotebookDoubleClickHidesWidgets") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_notebook_double_click_hides_widgets (object);
	} else if (strcmp (property_name, "HighlightingInvertAll") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_highlighting_invert_all (object);
	} else if (strcmp (property_name, "SidebarPos") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_sidebar_pos (object);
	} else if (strcmp (property_name, "MsgwinStatusVisible") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_msgwin_status_visible (object);
	} else if (strcmp (property_name, "MsgwinCompilerVisible") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_msgwin_compiler_visible (object);
	} else if (strcmp (property_name, "MsgwinMessagesVisible") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_msgwin_messages_visible (object);
	} else if (strcmp (property_name, "MsgwinScribbleVisible") == 0) {
		return _dbus_geany_dbus_interface_preferences_get_msgwin_scribble_visible (object);
	}
	return NULL;
}


static void _dbus_geany_dbus_interface_preferences_set_sidebar_symbol_visible (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_interface_preferences_set_sidebar_symbol_visible (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_sidebar_openfiles_visible (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_interface_preferences_set_sidebar_openfiles_visible (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_editor_font (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	char* value = NULL;
	value = g_variant_dup_string (_value, NULL);
	geany_dbus_interface_preferences_set_editor_font (self, value);
	_g_free0 (value);
}


static void _dbus_geany_dbus_interface_preferences_set_tagbar_font (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	char* value = NULL;
	value = g_variant_dup_string (_value, NULL);
	geany_dbus_interface_preferences_set_tagbar_font (self, value);
	_g_free0 (value);
}


static void _dbus_geany_dbus_interface_preferences_set_msgwin_font (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	char* value = NULL;
	value = g_variant_dup_string (_value, NULL);
	geany_dbus_interface_preferences_set_msgwin_font (self, value);
	_g_free0 (value);
}


static void _dbus_geany_dbus_interface_preferences_set_show_notebook_tabs (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_interface_preferences_set_show_notebook_tabs (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_tab_pos_editor (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gint value = 0;
	value = g_variant_get_int32 (_value);
	geany_dbus_interface_preferences_set_tab_pos_editor (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_tab_pos_msgwin (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gint value = 0;
	value = g_variant_get_int32 (_value);
	geany_dbus_interface_preferences_set_tab_pos_msgwin (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_tab_pos_sidebar (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gint value = 0;
	value = g_variant_get_int32 (_value);
	geany_dbus_interface_preferences_set_tab_pos_sidebar (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_statusbar_visible (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_interface_preferences_set_statusbar_visible (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_show_symbol_list_expanders (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_interface_preferences_set_show_symbol_list_expanders (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_notebook_double_click_hides_widgets (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_interface_preferences_set_notebook_double_click_hides_widgets (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_highlighting_invert_all (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_interface_preferences_set_highlighting_invert_all (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_sidebar_pos (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gint value = 0;
	value = g_variant_get_int32 (_value);
	geany_dbus_interface_preferences_set_sidebar_pos (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_msgwin_status_visible (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_interface_preferences_set_msgwin_status_visible (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_msgwin_compiler_visible (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_interface_preferences_set_msgwin_compiler_visible (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_msgwin_messages_visible (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_interface_preferences_set_msgwin_messages_visible (self, value);
}


static void _dbus_geany_dbus_interface_preferences_set_msgwin_scribble_visible (GeanyDBusInterfacePreferences* self, GVariant* _value) {
	gboolean value = FALSE;
	value = g_variant_get_boolean (_value);
	geany_dbus_interface_preferences_set_msgwin_scribble_visible (self, value);
}


static gboolean geany_dbus_interface_preferences_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (property_name, "SidebarSymbolVisible") == 0) {
		_dbus_geany_dbus_interface_preferences_set_sidebar_symbol_visible (object, value);
		return TRUE;
	} else if (strcmp (property_name, "SidebarOpenfilesVisible") == 0) {
		_dbus_geany_dbus_interface_preferences_set_sidebar_openfiles_visible (object, value);
		return TRUE;
	} else if (strcmp (property_name, "EditorFont") == 0) {
		_dbus_geany_dbus_interface_preferences_set_editor_font (object, value);
		return TRUE;
	} else if (strcmp (property_name, "TagbarFont") == 0) {
		_dbus_geany_dbus_interface_preferences_set_tagbar_font (object, value);
		return TRUE;
	} else if (strcmp (property_name, "MsgwinFont") == 0) {
		_dbus_geany_dbus_interface_preferences_set_msgwin_font (object, value);
		return TRUE;
	} else if (strcmp (property_name, "ShowNotebookTabs") == 0) {
		_dbus_geany_dbus_interface_preferences_set_show_notebook_tabs (object, value);
		return TRUE;
	} else if (strcmp (property_name, "TabPosEditor") == 0) {
		_dbus_geany_dbus_interface_preferences_set_tab_pos_editor (object, value);
		return TRUE;
	} else if (strcmp (property_name, "TabPosMsgwin") == 0) {
		_dbus_geany_dbus_interface_preferences_set_tab_pos_msgwin (object, value);
		return TRUE;
	} else if (strcmp (property_name, "TabPosSidebar") == 0) {
		_dbus_geany_dbus_interface_preferences_set_tab_pos_sidebar (object, value);
		return TRUE;
	} else if (strcmp (property_name, "StatusbarVisible") == 0) {
		_dbus_geany_dbus_interface_preferences_set_statusbar_visible (object, value);
		return TRUE;
	} else if (strcmp (property_name, "ShowSymbolListExpanders") == 0) {
		_dbus_geany_dbus_interface_preferences_set_show_symbol_list_expanders (object, value);
		return TRUE;
	} else if (strcmp (property_name, "NotebookDoubleClickHidesWidgets") == 0) {
		_dbus_geany_dbus_interface_preferences_set_notebook_double_click_hides_widgets (object, value);
		return TRUE;
	} else if (strcmp (property_name, "HighlightingInvertAll") == 0) {
		_dbus_geany_dbus_interface_preferences_set_highlighting_invert_all (object, value);
		return TRUE;
	} else if (strcmp (property_name, "SidebarPos") == 0) {
		_dbus_geany_dbus_interface_preferences_set_sidebar_pos (object, value);
		return TRUE;
	} else if (strcmp (property_name, "MsgwinStatusVisible") == 0) {
		_dbus_geany_dbus_interface_preferences_set_msgwin_status_visible (object, value);
		return TRUE;
	} else if (strcmp (property_name, "MsgwinCompilerVisible") == 0) {
		_dbus_geany_dbus_interface_preferences_set_msgwin_compiler_visible (object, value);
		return TRUE;
	} else if (strcmp (property_name, "MsgwinMessagesVisible") == 0) {
		_dbus_geany_dbus_interface_preferences_set_msgwin_messages_visible (object, value);
		return TRUE;
	} else if (strcmp (property_name, "MsgwinScribbleVisible") == 0) {
		_dbus_geany_dbus_interface_preferences_set_msgwin_scribble_visible (object, value);
		return TRUE;
	}
	return FALSE;
}


guint geany_dbus_interface_preferences_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, &_geany_dbus_interface_preferences_dbus_interface_info, &_geany_dbus_interface_preferences_dbus_interface_vtable, data, _geany_dbus_interface_preferences_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _geany_dbus_interface_preferences_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}




