/* project.c generated by valac 0.10.0, the Vala compiler
 * generated from project.vala, do not modify */

/*
 * project.vala - Geany project interface for DBus plugin
 * 
 * Copyright 2011 Matthew Brush <mbrush@leftclick.ca>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 */

#include <glib.h>
#include <glib-object.h>
#include "dbus-plugin.h"
#include <geanyplugin.h>
#include <gio/gio.h>

#define _g_free0(var) (var = (g_free (var), NULL))

struct _GeanyDBusProjectPrivate {
	GeanyProject* proj;
};


static gpointer geany_dbus_project_parent_class = NULL;

#define GEANY_DBUS_PROJECT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GEANY_DBUS_TYPE_PROJECT, GeanyDBusProjectPrivate))
enum  {
	GEANY_DBUS_PROJECT_DUMMY_PROPERTY,
	GEANY_DBUS_PROJECT_NAME,
	GEANY_DBUS_PROJECT_DESCRIPTION,
	GEANY_DBUS_PROJECT_FILE_NAME,
	GEANY_DBUS_PROJECT_BASE_PATH,
	GEANY_DBUS_PROJECT_PROJECT_TYPE
};
static void geany_dbus_project_finalize (GObject* obj);
static void geany_dbus_project_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void geany_dbus_project_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void geany_dbus_project_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* geany_dbus_project_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static GVariant* _dbus_geany_dbus_project_get_name (GeanyDBusProject* self);
static GVariant* _dbus_geany_dbus_project_get_description (GeanyDBusProject* self);
static GVariant* _dbus_geany_dbus_project_get_file_name (GeanyDBusProject* self);
static GVariant* _dbus_geany_dbus_project_get_base_path (GeanyDBusProject* self);
static GVariant* _dbus_geany_dbus_project_get_project_type (GeanyDBusProject* self);
static gboolean geany_dbus_project_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _dbus_geany_dbus_project_set_name (GeanyDBusProject* self, GVariant* _value);
static void _dbus_geany_dbus_project_set_description (GeanyDBusProject* self, GVariant* _value);
static void _dbus_geany_dbus_project_set_file_name (GeanyDBusProject* self, GVariant* _value);
static void _dbus_geany_dbus_project_set_base_path (GeanyDBusProject* self, GVariant* _value);
static void _dbus_geany_dbus_project_set_project_type (GeanyDBusProject* self, GVariant* _value);
static void _geany_dbus_project_unregister_object (gpointer user_data);

static const GDBusMethodInfo * const _geany_dbus_project_dbus_method_info[] = {NULL};
static const GDBusSignalInfo * const _geany_dbus_project_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo _geany_dbus_project_dbus_property_info_name = {-1, "Name", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_project_dbus_property_info_description = {-1, "Description", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_project_dbus_property_info_file_name = {-1, "FileName", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_project_dbus_property_info_base_path = {-1, "BasePath", "s", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo _geany_dbus_project_dbus_property_info_project_type = {-1, "ProjectType", "i", G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE};
static const GDBusPropertyInfo * const _geany_dbus_project_dbus_property_info[] = {&_geany_dbus_project_dbus_property_info_name, &_geany_dbus_project_dbus_property_info_description, &_geany_dbus_project_dbus_property_info_file_name, &_geany_dbus_project_dbus_property_info_base_path, &_geany_dbus_project_dbus_property_info_project_type, NULL};
static const GDBusInterfaceInfo _geany_dbus_project_dbus_interface_info = {-1, "org.geany.DBus.Interfaces.Project", (GDBusMethodInfo **) (&_geany_dbus_project_dbus_method_info), (GDBusSignalInfo **) (&_geany_dbus_project_dbus_signal_info), (GDBusPropertyInfo **) (&_geany_dbus_project_dbus_property_info)};
static const GDBusInterfaceVTable _geany_dbus_project_dbus_interface_vtable = {geany_dbus_project_dbus_interface_method_call, geany_dbus_project_dbus_interface_get_property, geany_dbus_project_dbus_interface_set_property};


GeanyDBusProject* geany_dbus_project_construct (GType object_type, GeanyProject* proj) {
	GeanyDBusProject * self;
	g_return_val_if_fail (proj != NULL, NULL);
	self = (GeanyDBusProject*) g_object_new (object_type, NULL);
	self->priv->proj = proj;
	return self;
}


GeanyDBusProject* geany_dbus_project_new (GeanyProject* proj) {
	return geany_dbus_project_construct (GEANY_DBUS_TYPE_PROJECT, proj);
}


const char* geany_dbus_project_get_name (GeanyDBusProject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->proj->name;
	return result;
}


void geany_dbus_project_set_name (GeanyDBusProject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->proj->name = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->proj->name), _tmp0_);
	g_object_notify ((GObject *) self, "name");
}


const char* geany_dbus_project_get_description (GeanyDBusProject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->proj->description;
	return result;
}


void geany_dbus_project_set_description (GeanyDBusProject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->proj->description = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->proj->description), _tmp0_);
	g_object_notify ((GObject *) self, "description");
}


const char* geany_dbus_project_get_file_name (GeanyDBusProject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->proj->file_name;
	return result;
}


void geany_dbus_project_set_file_name (GeanyDBusProject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->proj->file_name = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->proj->file_name), _tmp0_);
	g_object_notify ((GObject *) self, "file-name");
}


const char* geany_dbus_project_get_base_path (GeanyDBusProject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->proj->base_path;
	return result;
}


void geany_dbus_project_set_base_path (GeanyDBusProject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->proj->base_path = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->proj->base_path), _tmp0_);
	g_object_notify ((GObject *) self, "base-path");
}


gint geany_dbus_project_get_project_type (GeanyDBusProject* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->proj->type;
	return result;
}


void geany_dbus_project_set_project_type (GeanyDBusProject* self, gint value) {
	g_return_if_fail (self != NULL);
	self->priv->proj->type = value;
	g_object_notify ((GObject *) self, "project-type");
}


static void geany_dbus_project_class_init (GeanyDBusProjectClass * klass) {
	geany_dbus_project_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GeanyDBusProjectPrivate));
	G_OBJECT_CLASS (klass)->get_property = geany_dbus_project_get_property;
	G_OBJECT_CLASS (klass)->set_property = geany_dbus_project_set_property;
	G_OBJECT_CLASS (klass)->finalize = geany_dbus_project_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_PROJECT_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_PROJECT_DESCRIPTION, g_param_spec_string ("description", "description", "description", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_PROJECT_FILE_NAME, g_param_spec_string ("file-name", "file-name", "file-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_PROJECT_BASE_PATH, g_param_spec_string ("base-path", "base-path", "base-path", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_PROJECT_PROJECT_TYPE, g_param_spec_int ("project-type", "project-type", "project-type", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void geany_dbus_project_instance_init (GeanyDBusProject * self) {
	self->priv = GEANY_DBUS_PROJECT_GET_PRIVATE (self);
}


static void geany_dbus_project_finalize (GObject* obj) {
	GeanyDBusProject * self;
	self = GEANY_DBUS_PROJECT (obj);
	G_OBJECT_CLASS (geany_dbus_project_parent_class)->finalize (obj);
}


GType geany_dbus_project_get_type (void) {
	static volatile gsize geany_dbus_project_type_id__volatile = 0;
	if (g_once_init_enter (&geany_dbus_project_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GeanyDBusProjectClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) geany_dbus_project_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GeanyDBusProject), 0, (GInstanceInitFunc) geany_dbus_project_instance_init, NULL };
		GType geany_dbus_project_type_id;
		geany_dbus_project_type_id = g_type_register_static (G_TYPE_OBJECT, "GeanyDBusProject", &g_define_type_info, 0);
		g_once_init_leave (&geany_dbus_project_type_id__volatile, geany_dbus_project_type_id);
	}
	return geany_dbus_project_type_id__volatile;
}


static void geany_dbus_project_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GeanyDBusProject * self;
	self = GEANY_DBUS_PROJECT (object);
	switch (property_id) {
		case GEANY_DBUS_PROJECT_NAME:
		g_value_set_string (value, geany_dbus_project_get_name (self));
		break;
		case GEANY_DBUS_PROJECT_DESCRIPTION:
		g_value_set_string (value, geany_dbus_project_get_description (self));
		break;
		case GEANY_DBUS_PROJECT_FILE_NAME:
		g_value_set_string (value, geany_dbus_project_get_file_name (self));
		break;
		case GEANY_DBUS_PROJECT_BASE_PATH:
		g_value_set_string (value, geany_dbus_project_get_base_path (self));
		break;
		case GEANY_DBUS_PROJECT_PROJECT_TYPE:
		g_value_set_int (value, geany_dbus_project_get_project_type (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void geany_dbus_project_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GeanyDBusProject * self;
	self = GEANY_DBUS_PROJECT (object);
	switch (property_id) {
		case GEANY_DBUS_PROJECT_NAME:
		geany_dbus_project_set_name (self, g_value_get_string (value));
		break;
		case GEANY_DBUS_PROJECT_DESCRIPTION:
		geany_dbus_project_set_description (self, g_value_get_string (value));
		break;
		case GEANY_DBUS_PROJECT_FILE_NAME:
		geany_dbus_project_set_file_name (self, g_value_get_string (value));
		break;
		case GEANY_DBUS_PROJECT_BASE_PATH:
		geany_dbus_project_set_base_path (self, g_value_get_string (value));
		break;
		case GEANY_DBUS_PROJECT_PROJECT_TYPE:
		geany_dbus_project_set_project_type (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void geany_dbus_project_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
}


static GVariant* _dbus_geany_dbus_project_get_name (GeanyDBusProject* self) {
	const char* result;
	GVariant* _reply;
	result = geany_dbus_project_get_name (self);
	_reply = g_variant_new_string (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_project_get_description (GeanyDBusProject* self) {
	const char* result;
	GVariant* _reply;
	result = geany_dbus_project_get_description (self);
	_reply = g_variant_new_string (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_project_get_file_name (GeanyDBusProject* self) {
	const char* result;
	GVariant* _reply;
	result = geany_dbus_project_get_file_name (self);
	_reply = g_variant_new_string (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_project_get_base_path (GeanyDBusProject* self) {
	const char* result;
	GVariant* _reply;
	result = geany_dbus_project_get_base_path (self);
	_reply = g_variant_new_string (result);
	return _reply;
}


static GVariant* _dbus_geany_dbus_project_get_project_type (GeanyDBusProject* self) {
	gint result;
	GVariant* _reply;
	result = geany_dbus_project_get_project_type (self);
	_reply = g_variant_new_int32 (result);
	return _reply;
}


static GVariant* geany_dbus_project_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (property_name, "Name") == 0) {
		return _dbus_geany_dbus_project_get_name (object);
	} else if (strcmp (property_name, "Description") == 0) {
		return _dbus_geany_dbus_project_get_description (object);
	} else if (strcmp (property_name, "FileName") == 0) {
		return _dbus_geany_dbus_project_get_file_name (object);
	} else if (strcmp (property_name, "BasePath") == 0) {
		return _dbus_geany_dbus_project_get_base_path (object);
	} else if (strcmp (property_name, "ProjectType") == 0) {
		return _dbus_geany_dbus_project_get_project_type (object);
	}
	return NULL;
}


static void _dbus_geany_dbus_project_set_name (GeanyDBusProject* self, GVariant* _value) {
	char* value = NULL;
	value = g_variant_dup_string (_value, NULL);
	geany_dbus_project_set_name (self, value);
	_g_free0 (value);
}


static void _dbus_geany_dbus_project_set_description (GeanyDBusProject* self, GVariant* _value) {
	char* value = NULL;
	value = g_variant_dup_string (_value, NULL);
	geany_dbus_project_set_description (self, value);
	_g_free0 (value);
}


static void _dbus_geany_dbus_project_set_file_name (GeanyDBusProject* self, GVariant* _value) {
	char* value = NULL;
	value = g_variant_dup_string (_value, NULL);
	geany_dbus_project_set_file_name (self, value);
	_g_free0 (value);
}


static void _dbus_geany_dbus_project_set_base_path (GeanyDBusProject* self, GVariant* _value) {
	char* value = NULL;
	value = g_variant_dup_string (_value, NULL);
	geany_dbus_project_set_base_path (self, value);
	_g_free0 (value);
}


static void _dbus_geany_dbus_project_set_project_type (GeanyDBusProject* self, GVariant* _value) {
	gint value = 0;
	value = g_variant_get_int32 (_value);
	geany_dbus_project_set_project_type (self, value);
}


static gboolean geany_dbus_project_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (property_name, "Name") == 0) {
		_dbus_geany_dbus_project_set_name (object, value);
		return TRUE;
	} else if (strcmp (property_name, "Description") == 0) {
		_dbus_geany_dbus_project_set_description (object, value);
		return TRUE;
	} else if (strcmp (property_name, "FileName") == 0) {
		_dbus_geany_dbus_project_set_file_name (object, value);
		return TRUE;
	} else if (strcmp (property_name, "BasePath") == 0) {
		_dbus_geany_dbus_project_set_base_path (object, value);
		return TRUE;
	} else if (strcmp (property_name, "ProjectType") == 0) {
		_dbus_geany_dbus_project_set_project_type (object, value);
		return TRUE;
	}
	return FALSE;
}


guint geany_dbus_project_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, &_geany_dbus_project_dbus_interface_info, &_geany_dbus_project_dbus_interface_vtable, data, _geany_dbus_project_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _geany_dbus_project_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}




