/* server.c generated by valac 0.10.0, the Vala compiler
 * generated from server.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "dbus-plugin.h"
#include <gio/gio.h>
#include <geanyplugin.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _GeanyDBusServerPrivate {
	GDBusConnection* conn;
	GeanyPlugin* plugin;
	GeanyData* data;
	GeanyFunctions* functions;
	GeanyDBusApplication* _application;
	GeanyDBusInterfacePreferences* _interface_prefs;
	GeanyDBusProject* _project;
	guint bus_id;
	guint* registered_objects;
	gint registered_objects_length1;
	gint _registered_objects_size_;
	GeeArrayList* registered_documents;
	gboolean documents_initialized;
};


static gpointer geany_dbus_server_parent_class = NULL;

#define GEANY_DBUS_SERVER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GEANY_DBUS_TYPE_SERVER, GeanyDBusServerPrivate))
enum  {
	GEANY_DBUS_SERVER_DUMMY_PROPERTY,
	GEANY_DBUS_SERVER_APPLICATION,
	GEANY_DBUS_SERVER_INTERFACE_PREFS,
	GEANY_DBUS_SERVER_PROJECT
};
static void geany_dbus_server_on_bus_acquired (GeanyDBusServer* self, GDBusConnection* conn);
static void _geany_dbus_server_on_bus_acquired_gbus_acquired_callback (GDBusConnection* connection, const char* name, gpointer self);
static void geany_dbus_server_on_bus_name_acquired (GeanyDBusServer* self, GDBusConnection* conn, const char* name);
static void _geany_dbus_server_on_bus_name_acquired_gbus_name_acquired_callback (GDBusConnection* connection, const char* name, gpointer self);
static void geany_dbus_server_on_bus_name_lost (GeanyDBusServer* self, GDBusConnection* conn, const char* name);
static void _geany_dbus_server_on_bus_name_lost_gbus_name_lost_callback (GDBusConnection* connection, const char* name, gpointer self);
static void geany_dbus_server_initialize_documents (GeanyDBusServer* self);
void geany_dbus_document_set_dbus_index (GeanyDBusDocument* self, guint value);
guint geany_dbus_document_get_dbus_index (GeanyDBusDocument* self);
static void _vala_array_add1 (guint** array, int* length, int* size, guint value);
static void _vala_array_add2 (guint** array, int* length, int* size, guint value);
static void _vala_array_add3 (guint** array, int* length, int* size, guint value);
static void geany_dbus_server_finalize (GObject* obj);
static void geany_dbus_server_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void geany_dbus_server_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);



static void _geany_dbus_server_on_bus_acquired_gbus_acquired_callback (GDBusConnection* connection, const char* name, gpointer self) {
	geany_dbus_server_on_bus_acquired (self, connection);
}


static void _geany_dbus_server_on_bus_name_acquired_gbus_name_acquired_callback (GDBusConnection* connection, const char* name, gpointer self) {
	geany_dbus_server_on_bus_name_acquired (self, connection, name);
}


static void _geany_dbus_server_on_bus_name_lost_gbus_name_lost_callback (GDBusConnection* connection, const char* name, gpointer self) {
	geany_dbus_server_on_bus_name_lost (self, connection, name);
}


GeanyDBusServer* geany_dbus_server_construct (GType object_type, GeanyPlugin* plugin, GeanyData* data, GeanyFunctions* functions) {
	GeanyDBusServer * self;
	GeanyDBusApplication* _tmp0_;
	GeanyDBusInterfacePreferences* _tmp1_;
	GeanyDBusProject* _tmp2_;
	guint* _tmp3_ = NULL;
	guint* _tmp4_;
	GeeArrayList* _tmp5_;
	g_return_val_if_fail (plugin != NULL, NULL);
	g_return_val_if_fail (data != NULL, NULL);
	g_return_val_if_fail (functions != NULL, NULL);
	self = (GeanyDBusServer*) g_object_new (object_type, NULL);
	self->priv->plugin = plugin;
	self->priv->data = data;
	self->priv->functions = functions;
	geany_dbus_server_set_application (self, _tmp0_ = geany_dbus_application_new (data->app));
	_g_object_unref0 (_tmp0_);
	geany_dbus_server_set_interface_prefs (self, _tmp1_ = geany_dbus_interface_preferences_new (data->interface_prefs));
	_g_object_unref0 (_tmp1_);
	geany_dbus_server_set_project (self, _tmp2_ = geany_dbus_project_new (data->app->project));
	_g_object_unref0 (_tmp2_);
	self->priv->registered_objects = (_tmp4_ = (_tmp3_ = g_new0 (guint, 0), _tmp3_), self->priv->registered_objects = (g_free (self->priv->registered_objects), NULL), self->priv->registered_objects_length1 = 0, self->priv->_registered_objects_size_ = self->priv->registered_objects_length1, _tmp4_);
	self->priv->registered_documents = (_tmp5_ = gee_array_list_new (GEANY_DBUS_TYPE_DOCUMENT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL), _g_object_unref0 (self->priv->registered_documents), _tmp5_);
	self->priv->documents_initialized = FALSE;
	self->instance_number = 0;
	self->priv->bus_id = g_bus_own_name_with_closures (G_BUS_TYPE_SESSION, GEANY_DBUS_NAME, G_BUS_NAME_OWNER_FLAGS_NONE, (GClosure*) g_cclosure_new ((GCallback) _geany_dbus_server_on_bus_acquired_gbus_acquired_callback, g_object_ref (self), g_object_unref), (GClosure*) g_cclosure_new ((GCallback) _geany_dbus_server_on_bus_name_acquired_gbus_name_acquired_callback, g_object_ref (self), g_object_unref), (GClosure*) g_cclosure_new ((GCallback) _geany_dbus_server_on_bus_name_lost_gbus_name_lost_callback, g_object_ref (self), g_object_unref));
	plugin_signal_connect (self->priv->plugin, NULL, "document-new", TRUE, (GCallback) geany_dbus_server_on_document_open_new, self);
	plugin_signal_connect (self->priv->plugin, NULL, "document-open", TRUE, (GCallback) geany_dbus_server_on_document_open_new, self);
	plugin_signal_connect (self->priv->plugin, NULL, "document-close", TRUE, (GCallback) geany_dbus_server_on_document_close, self);
	plugin_signal_connect (self->priv->plugin, NULL, "document-save", TRUE, (GCallback) geany_dbus_server_on_document_save, self);
	plugin_signal_connect (self->priv->plugin, NULL, "document-before-save", TRUE, (GCallback) geany_dbus_server_on_document_before_save, self);
	return self;
}


GeanyDBusServer* geany_dbus_server_new (GeanyPlugin* plugin, GeanyData* data, GeanyFunctions* functions) {
	return geany_dbus_server_construct (GEANY_DBUS_TYPE_SERVER, plugin, data, functions);
}


void geany_dbus_server_close (GeanyDBusServer* self) {
	guint* _tmp1_ = NULL;
	guint* _tmp2_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				if (!_tmp0_) {
					i++;
				}
				_tmp0_ = FALSE;
				if (!(i < self->priv->registered_objects_length1)) {
					break;
				}
				if (!g_dbus_connection_unregister_object (self->priv->conn, self->priv->registered_objects[i])) {
					g_warning ("server.vala:97: Failed to unregister object id %d", (gint) self->priv->registered_objects[i]);
				}
			}
		}
	}
	self->priv->registered_objects = (_tmp2_ = (_tmp1_ = g_new0 (guint, 0), _tmp1_), self->priv->registered_objects = (g_free (self->priv->registered_objects), NULL), self->priv->registered_objects_length1 = 0, self->priv->_registered_objects_size_ = self->priv->registered_objects_length1, _tmp2_);
	g_bus_unown_name (self->priv->bus_id);
	{
		g_dbus_connection_close_sync (self->priv->conn, NULL, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
		ui_set_statusbar (TRUE, "DBus server stopped.");
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_debug ("server.vala:107: Error closing DBus connection: %s\n", e->message);
			_g_error_free0 (e);
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static gint __geany_vala_plugin_document_get_index (struct GeanyDocument* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->index;
	return result;
}


static void geany_dbus_server_initialize_documents (GeanyDBusServer* self) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	if (!self->priv->documents_initialized) {
		{
			struct GeanyDocument** doc_collection;
			int doc_collection_length1;
			int doc_it;
			doc_collection = documents;
			doc_collection_length1 = GEANY(documents_array)->len;
			for (doc_it = 0; doc_it < GEANY(documents_array)->len; doc_it = doc_it + 1) {
				struct GeanyDocument* doc;
				doc = doc_collection[doc_it];
				{
					{
						GeanyDBusDocument* dbus_doc;
						char* obj_path;
						char* _tmp0_;
						guint _tmp1_;
						dbus_doc = geany_dbus_document_new (doc);
						obj_path = NULL;
						obj_path = (_tmp0_ = g_strdup_printf ("/org/geany/DBus/Documents/%d", __geany_vala_plugin_document_get_index (doc)), _g_free0 (obj_path), _tmp0_);
						_tmp1_ = geany_dbus_document_register_object (dbus_doc, self->priv->conn, obj_path, &_inner_error_);
						if (_inner_error_ != NULL) {
							_g_free0 (obj_path);
							_g_object_unref0 (dbus_doc);
							if (_inner_error_->domain == G_IO_ERROR) {
								goto __catch1_g_io_error;
							}
							_g_free0 (obj_path);
							_g_object_unref0 (dbus_doc);
							g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
							g_clear_error (&_inner_error_);
							return;
						}
						geany_dbus_document_set_dbus_index (dbus_doc, _tmp1_);
						if (geany_dbus_document_get_dbus_index (dbus_doc) > 0) {
							gee_abstract_collection_add ((GeeAbstractCollection*) self->priv->registered_documents, dbus_doc);
							g_debug ("server.vala:127: Registered document: %s", geany_dbus_document_get_file_name (dbus_doc));
						} else {
							g_warning ("server.vala:130: Failed to register document: %s", geany_dbus_document_get_file_name (dbus_doc));
						}
						_g_free0 (obj_path);
						_g_object_unref0 (dbus_doc);
					}
					goto __finally1;
					__catch1_g_io_error:
					{
						GError * e;
						e = _inner_error_;
						_inner_error_ = NULL;
						{
							g_warning ("server.vala:135: Error registering object with DBus: %s", e->message);
							_g_error_free0 (e);
						}
					}
					__finally1:
					if (_inner_error_ != NULL) {
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
				}
			}
		}
		self->priv->documents_initialized = TRUE;
		g_debug ("server.vala:139: Documents initialized");
	}
}


static void _vala_array_add1 (guint** array, int* length, int* size, guint value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (guint, *array, *size);
	}
	(*array)[(*length)++] = value;
}


static void _vala_array_add2 (guint** array, int* length, int* size, guint value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (guint, *array, *size);
	}
	(*array)[(*length)++] = value;
}


static void _vala_array_add3 (guint** array, int* length, int* size, guint value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (guint, *array, *size);
	}
	(*array)[(*length)++] = value;
}


static void geany_dbus_server_on_bus_acquired (GeanyDBusServer* self, GDBusConnection* conn) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (conn != NULL);
	self->priv->conn = conn;
	{
		guint _tmp0_;
		guint _tmp1_;
		guint _tmp2_;
		_tmp0_ = geany_dbus_application_register_object (self->priv->_application, conn, "/org/geany/DBus/Application", &_inner_error_);
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_IO_ERROR) {
				goto __catch2_g_io_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_vala_array_add1 (&self->priv->registered_objects, &self->priv->registered_objects_length1, &self->priv->_registered_objects_size_, _tmp0_);
		_tmp1_ = geany_dbus_project_register_object (self->priv->_project, conn, "/org/geany/DBus/Project", &_inner_error_);
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_IO_ERROR) {
				goto __catch2_g_io_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_vala_array_add2 (&self->priv->registered_objects, &self->priv->registered_objects_length1, &self->priv->_registered_objects_size_, _tmp1_);
		_tmp2_ = geany_dbus_interface_preferences_register_object (self->priv->_interface_prefs, conn, "/org/geany/DBus/UI/Preferences", &_inner_error_);
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_IO_ERROR) {
				goto __catch2_g_io_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_vala_array_add3 (&self->priv->registered_objects, &self->priv->registered_objects_length1, &self->priv->_registered_objects_size_, _tmp2_);
		if (!self->priv->documents_initialized) {
			geany_dbus_server_initialize_documents (self);
		}
	}
	goto __finally2;
	__catch2_g_io_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("server.vala:164: Could not register services: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally2:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void geany_dbus_server_on_bus_name_acquired (GeanyDBusServer* self, GDBusConnection* conn, const char* name) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (conn != NULL);
	g_return_if_fail (name != NULL);
	ui_set_statusbar (TRUE, "DBus server started with bus name '%s'.", name);
}


static void geany_dbus_server_on_bus_name_lost (GeanyDBusServer* self, GDBusConnection* conn, const char* name) {
	char* new_bus_name;
	g_return_if_fail (self != NULL);
	g_return_if_fail (conn != NULL);
	g_return_if_fail (name != NULL);
	if (self->instance_number > 255) {
		ui_set_statusbar (TRUE, "DBus server started, but could not " "own bus name, so using unique name: %s", g_dbus_connection_get_unique_name (conn));
		return;
	}
	self->instance_number++;
	new_bus_name = g_strdup_printf ("%s.Instance%d", GEANY_DBUS_NAME, self->instance_number);
	g_debug ("server.vala:190: Attempting name %s", new_bus_name);
	self->priv->bus_id = g_bus_own_name_with_closures (G_BUS_TYPE_SESSION, new_bus_name, G_BUS_NAME_OWNER_FLAGS_NONE, (GClosure*) g_cclosure_new ((GCallback) _geany_dbus_server_on_bus_acquired_gbus_acquired_callback, g_object_ref (self), g_object_unref), (GClosure*) g_cclosure_new ((GCallback) _geany_dbus_server_on_bus_name_acquired_gbus_name_acquired_callback, g_object_ref (self), g_object_unref), (GClosure*) g_cclosure_new ((GCallback) _geany_dbus_server_on_bus_name_lost_gbus_name_lost_callback, g_object_ref (self), g_object_unref));
	_g_free0 (new_bus_name);
}


void geany_dbus_server_on_document_open_new (GObject* object, struct GeanyDocument* doc, GeanyDBusServer* self) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (object != NULL);
	g_return_if_fail (doc != NULL);
	if (self->priv->documents_initialized) {
		GeanyDBusDocument* dbus_doc;
		dbus_doc = geany_dbus_document_new (doc);
		{
			char* obj_path;
			char* _tmp0_;
			guint _tmp1_;
			obj_path = NULL;
			obj_path = (_tmp0_ = g_strdup_printf ("/org/geany/DBus/Documents/%d", __geany_vala_plugin_document_get_index (doc)), _g_free0 (obj_path), _tmp0_);
			_tmp1_ = geany_dbus_document_register_object (dbus_doc, self->priv->conn, obj_path, &_inner_error_);
			if (_inner_error_ != NULL) {
				_g_free0 (obj_path);
				if (_inner_error_->domain == G_IO_ERROR) {
					goto __catch3_g_io_error;
				}
				_g_free0 (obj_path);
				_g_object_unref0 (dbus_doc);
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
			geany_dbus_document_set_dbus_index (dbus_doc, _tmp1_);
			if (geany_dbus_document_get_dbus_index (dbus_doc) > 0) {
				gee_abstract_collection_add ((GeeAbstractCollection*) self->priv->registered_documents, dbus_doc);
				g_debug ("server.vala:214: Registered document: %s", geany_dbus_document_get_file_name (dbus_doc));
			} else {
				g_warning ("server.vala:217: Failed to register document: %s", geany_dbus_document_get_file_name (dbus_doc));
			}
			_g_free0 (obj_path);
		}
		goto __finally3;
		__catch3_g_io_error:
		{
			GError * e;
			e = _inner_error_;
			_inner_error_ = NULL;
			{
				g_warning ("server.vala:222: Error registering object with DBus: %s", e->message);
				_g_error_free0 (e);
			}
		}
		__finally3:
		if (_inner_error_ != NULL) {
			_g_object_unref0 (dbus_doc);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		_g_object_unref0 (dbus_doc);
	} else {
		g_debug ("server.vala:226: Document initialization pending");
	}
}


void geany_dbus_server_on_document_close (GObject* object, struct GeanyDocument* doc, GeanyDBusServer* self) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (object != NULL);
	g_return_if_fail (doc != NULL);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				GeanyDBusDocument* dbus_doc;
				if (!_tmp0_) {
					i++;
				}
				_tmp0_ = FALSE;
				if (!(i < gee_collection_get_size ((GeeCollection*) self->priv->registered_documents))) {
					break;
				}
				dbus_doc = (GeanyDBusDocument*) gee_abstract_list_get ((GeeAbstractList*) self->priv->registered_documents, i);
				if (geany_dbus_document_get_index (dbus_doc) == __geany_vala_plugin_document_get_index (doc)) {
					g_signal_emit_by_name (dbus_doc, "before-close");
					if (g_dbus_connection_unregister_object (self->priv->conn, geany_dbus_document_get_dbus_index (dbus_doc))) {
						GeanyDBusDocument* _tmp1_;
						_tmp1_ = (GeanyDBusDocument*) gee_abstract_list_remove_at ((GeeAbstractList*) self->priv->registered_documents, i);
						_g_object_unref0 (_tmp1_);
						g_debug ("server.vala:241: Unregistered document\n");
					} else {
						g_warning ("server.vala:244: Error unregistering doc id %d", geany_dbus_document_get_index (dbus_doc));
					}
				}
				_g_object_unref0 (dbus_doc);
			}
		}
	}
}


void geany_dbus_server_on_document_save (GObject* object, struct GeanyDocument* doc, GeanyDBusServer* self) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (object != NULL);
	g_return_if_fail (doc != NULL);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				GeanyDBusDocument* dbus_doc;
				if (!_tmp0_) {
					i++;
				}
				_tmp0_ = FALSE;
				if (!(i < gee_collection_get_size ((GeeCollection*) self->priv->registered_documents))) {
					break;
				}
				dbus_doc = (GeanyDBusDocument*) gee_abstract_list_get ((GeeAbstractList*) self->priv->registered_documents, i);
				if (geany_dbus_document_get_index (dbus_doc) == __geany_vala_plugin_document_get_index (doc)) {
					g_signal_emit_by_name (dbus_doc, "saved");
				}
				_g_object_unref0 (dbus_doc);
			}
		}
	}
}


void geany_dbus_server_on_document_before_save (GObject* object, struct GeanyDocument* doc, GeanyDBusServer* self) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (object != NULL);
	g_return_if_fail (doc != NULL);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				GeanyDBusDocument* dbus_doc;
				if (!_tmp0_) {
					i++;
				}
				_tmp0_ = FALSE;
				if (!(i < gee_collection_get_size ((GeeCollection*) self->priv->registered_documents))) {
					break;
				}
				dbus_doc = (GeanyDBusDocument*) gee_abstract_list_get ((GeeAbstractList*) self->priv->registered_documents, i);
				if (geany_dbus_document_get_index (dbus_doc) == __geany_vala_plugin_document_get_index (doc)) {
					g_signal_emit_by_name (dbus_doc, "before-save");
				}
				_g_object_unref0 (dbus_doc);
			}
		}
	}
}


GeanyDBusApplication* geany_dbus_server_get_application (GeanyDBusServer* self) {
	GeanyDBusApplication* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_application;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void geany_dbus_server_set_application (GeanyDBusServer* self, GeanyDBusApplication* value) {
	GeanyDBusApplication* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_application = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_application), _tmp0_);
	g_object_notify ((GObject *) self, "application");
}


GeanyDBusInterfacePreferences* geany_dbus_server_get_interface_prefs (GeanyDBusServer* self) {
	GeanyDBusInterfacePreferences* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_interface_prefs;
	return result;
}


void geany_dbus_server_set_interface_prefs (GeanyDBusServer* self, GeanyDBusInterfacePreferences* value) {
	GeanyDBusInterfacePreferences* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_interface_prefs = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_interface_prefs), _tmp0_);
	g_object_notify ((GObject *) self, "interface-prefs");
}


GeanyDBusProject* geany_dbus_server_get_project (GeanyDBusServer* self) {
	GeanyDBusProject* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_project;
	return result;
}


void geany_dbus_server_set_project (GeanyDBusServer* self, GeanyDBusProject* value) {
	GeanyDBusProject* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_project = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_project), _tmp0_);
	g_object_notify ((GObject *) self, "project");
}


static void geany_dbus_server_class_init (GeanyDBusServerClass * klass) {
	geany_dbus_server_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GeanyDBusServerPrivate));
	G_OBJECT_CLASS (klass)->get_property = geany_dbus_server_get_property;
	G_OBJECT_CLASS (klass)->set_property = geany_dbus_server_set_property;
	G_OBJECT_CLASS (klass)->finalize = geany_dbus_server_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_SERVER_APPLICATION, g_param_spec_object ("application", "application", "application", GEANY_DBUS_TYPE_APPLICATION, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_SERVER_INTERFACE_PREFS, g_param_spec_object ("interface-prefs", "interface-prefs", "interface-prefs", GEANY_DBUS_TYPE_INTERFACE_PREFERENCES, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEANY_DBUS_SERVER_PROJECT, g_param_spec_object ("project", "project", "project", GEANY_DBUS_TYPE_PROJECT, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void geany_dbus_server_instance_init (GeanyDBusServer * self) {
	self->priv = GEANY_DBUS_SERVER_GET_PRIVATE (self);
	self->priv->bus_id = (guint) 0;
}


static void geany_dbus_server_finalize (GObject* obj) {
	GeanyDBusServer * self;
	self = GEANY_DBUS_SERVER (obj);
	_g_object_unref0 (self->priv->_application);
	_g_object_unref0 (self->priv->_interface_prefs);
	_g_object_unref0 (self->priv->_project);
	self->priv->registered_objects = (g_free (self->priv->registered_objects), NULL);
	_g_object_unref0 (self->priv->registered_documents);
	G_OBJECT_CLASS (geany_dbus_server_parent_class)->finalize (obj);
}


GType geany_dbus_server_get_type (void) {
	static volatile gsize geany_dbus_server_type_id__volatile = 0;
	if (g_once_init_enter (&geany_dbus_server_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GeanyDBusServerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) geany_dbus_server_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GeanyDBusServer), 0, (GInstanceInitFunc) geany_dbus_server_instance_init, NULL };
		GType geany_dbus_server_type_id;
		geany_dbus_server_type_id = g_type_register_static (G_TYPE_OBJECT, "GeanyDBusServer", &g_define_type_info, 0);
		g_once_init_leave (&geany_dbus_server_type_id__volatile, geany_dbus_server_type_id);
	}
	return geany_dbus_server_type_id__volatile;
}


static void geany_dbus_server_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GeanyDBusServer * self;
	self = GEANY_DBUS_SERVER (object);
	switch (property_id) {
		case GEANY_DBUS_SERVER_APPLICATION:
		g_value_set_object (value, geany_dbus_server_get_application (self));
		break;
		case GEANY_DBUS_SERVER_INTERFACE_PREFS:
		g_value_set_object (value, geany_dbus_server_get_interface_prefs (self));
		break;
		case GEANY_DBUS_SERVER_PROJECT:
		g_value_set_object (value, geany_dbus_server_get_project (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void geany_dbus_server_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GeanyDBusServer * self;
	self = GEANY_DBUS_SERVER (object);
	switch (property_id) {
		case GEANY_DBUS_SERVER_APPLICATION:
		geany_dbus_server_set_application (self, g_value_get_object (value));
		break;
		case GEANY_DBUS_SERVER_INTERFACE_PREFS:
		geany_dbus_server_set_interface_prefs (self, g_value_get_object (value));
		break;
		case GEANY_DBUS_SERVER_PROJECT:
		geany_dbus_server_set_project (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




