/* widgets.c generated by valac 0.10.0, the Vala compiler
 * generated from widgets.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "dbus-plugin.h"
#include <geanyplugin.h>
#include <gio/gio.h>


struct _GeanyDBusWidgetsPrivate {
	GeanyMainWidgets* widgets;
};


static gpointer geany_dbus_widgets_parent_class = NULL;

#define GEANY_DBUS_WIDGETS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GEANY_DBUS_TYPE_WIDGETS, GeanyDBusWidgetsPrivate))
enum  {
	GEANY_DBUS_WIDGETS_DUMMY_PROPERTY
};
static void geany_dbus_widgets_finalize (GObject* obj);
static void geany_dbus_widgets_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* geany_dbus_widgets_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean geany_dbus_widgets_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _geany_dbus_widgets_unregister_object (gpointer user_data);

static const GDBusMethodInfo * const _geany_dbus_widgets_dbus_method_info[] = {NULL};
static const GDBusSignalInfo * const _geany_dbus_widgets_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _geany_dbus_widgets_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _geany_dbus_widgets_dbus_interface_info = {-1, "org.geany.DBus.Widgets", (GDBusMethodInfo **) (&_geany_dbus_widgets_dbus_method_info), (GDBusSignalInfo **) (&_geany_dbus_widgets_dbus_signal_info), (GDBusPropertyInfo **) (&_geany_dbus_widgets_dbus_property_info)};
static const GDBusInterfaceVTable _geany_dbus_widgets_dbus_interface_vtable = {geany_dbus_widgets_dbus_interface_method_call, geany_dbus_widgets_dbus_interface_get_property, geany_dbus_widgets_dbus_interface_set_property};


GeanyDBusWidgets* geany_dbus_widgets_construct (GType object_type, GeanyMainWidgets* widgets) {
	GeanyDBusWidgets * self;
	g_return_val_if_fail (widgets != NULL, NULL);
	self = (GeanyDBusWidgets*) g_object_new (object_type, NULL);
	self->priv->widgets = widgets;
	return self;
}


GeanyDBusWidgets* geany_dbus_widgets_new (GeanyMainWidgets* widgets) {
	return geany_dbus_widgets_construct (GEANY_DBUS_TYPE_WIDGETS, widgets);
}


static void geany_dbus_widgets_class_init (GeanyDBusWidgetsClass * klass) {
	geany_dbus_widgets_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GeanyDBusWidgetsPrivate));
	G_OBJECT_CLASS (klass)->finalize = geany_dbus_widgets_finalize;
}


static void geany_dbus_widgets_instance_init (GeanyDBusWidgets * self) {
	self->priv = GEANY_DBUS_WIDGETS_GET_PRIVATE (self);
}


static void geany_dbus_widgets_finalize (GObject* obj) {
	GeanyDBusWidgets * self;
	self = GEANY_DBUS_WIDGETS (obj);
	G_OBJECT_CLASS (geany_dbus_widgets_parent_class)->finalize (obj);
}


GType geany_dbus_widgets_get_type (void) {
	static volatile gsize geany_dbus_widgets_type_id__volatile = 0;
	if (g_once_init_enter (&geany_dbus_widgets_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GeanyDBusWidgetsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) geany_dbus_widgets_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GeanyDBusWidgets), 0, (GInstanceInitFunc) geany_dbus_widgets_instance_init, NULL };
		GType geany_dbus_widgets_type_id;
		geany_dbus_widgets_type_id = g_type_register_static (G_TYPE_OBJECT, "GeanyDBusWidgets", &g_define_type_info, 0);
		g_once_init_leave (&geany_dbus_widgets_type_id__volatile, geany_dbus_widgets_type_id);
	}
	return geany_dbus_widgets_type_id__volatile;
}


static void geany_dbus_widgets_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
}


static GVariant* geany_dbus_widgets_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean geany_dbus_widgets_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint geany_dbus_widgets_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, &_geany_dbus_widgets_dbus_interface_info, &_geany_dbus_widgets_dbus_interface_vtable, data, _geany_dbus_widgets_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _geany_dbus_widgets_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}




